<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 R Markdown | Marketing Analytics 2022</title>
  <meta name="description" content="An Introduction to Data Analytics Using R" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="10 R Markdown | Marketing Analytics 2022" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="An Introduction to Data Analytics Using R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 R Markdown | Marketing Analytics 2022" />
  
  <meta name="twitter:description" content="An Introduction to Data Analytics Using R" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="cluster-analysis.html"/>
<link rel="next" href="survey-design-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">MA 2022/23</a></strong></li>

<li class="divider"></li>
<li class="part"><span><b>I Course outline</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#course-structure"><i class="fa fa-check"></i>Course structure</a>
<ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#schedule"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#grading"><i class="fa fa-check"></i>Grading</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#course-materials"><i class="fa fa-check"></i>Course materials</a>
<ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#main-reference"><i class="fa fa-check"></i>Main reference</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#further-readings"><i class="fa fa-check"></i>Further readings</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#discussion-forum"><i class="fa fa-check"></i>Discussion forum</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#datacamp"><i class="fa fa-check"></i>DataCamp</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#other-web-resources"><i class="fa fa-check"></i>Other web-resources</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#contact"><i class="fa fa-check"></i>Contact</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Lecture notes</b></span></li>
<li class="chapter" data-level="1" data-path="preliminaries.html"><a href="preliminaries.html"><i class="fa fa-check"></i><b>1</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="1.1" data-path="preliminaries.html"><a href="preliminaries.html#marketing-foundations-recap"><i class="fa fa-check"></i><b>1.1</b> Marketing foundations (recap)</a></li>
<li class="chapter" data-level="1.2" data-path="preliminaries.html"><a href="preliminaries.html#the-research-process"><i class="fa fa-check"></i><b>1.2</b> The research process</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="preliminaries.html"><a href="preliminaries.html#research-question-and-hypothesis"><i class="fa fa-check"></i><b>1.2.1</b> Research question and hypothesis</a></li>
<li class="chapter" data-level="1.2.2" data-path="preliminaries.html"><a href="preliminaries.html#choosing-a-research-design"><i class="fa fa-check"></i><b>1.2.2</b> Choosing a research design</a></li>
<li class="chapter" data-level="1.2.3" data-path="preliminaries.html"><a href="preliminaries.html#collecting-data"><i class="fa fa-check"></i><b>1.2.3</b> Collecting data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="preliminaries.html"><a href="preliminaries.html#learning-check"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="preliminaries.html"><a href="preliminaries.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html"><i class="fa fa-check"></i><b>2</b> Getting started with R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#how-to-download-and-install-r-and-rstudio"><i class="fa fa-check"></i><b>2.1</b> How to download and install R and RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#the-r-studio-interface"><i class="fa fa-check"></i><b>2.2</b> The R Studio interface</a></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#functions"><i class="fa fa-check"></i><b>2.3</b> Functions</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#packages"><i class="fa fa-check"></i><b>2.4</b> Packages</a></li>
<li class="chapter" data-level="2.5" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#a-typical-r-session"><i class="fa fa-check"></i><b>2.5</b> A typical R session</a></li>
<li class="chapter" data-level="2.6" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#getting-help"><i class="fa fa-check"></i><b>2.6</b> Getting help</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-handling.html"><a href="data-handling.html"><i class="fa fa-check"></i><b>3</b> Data handling</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-handling.html"><a href="data-handling.html#basic-data-handling"><i class="fa fa-check"></i><b>3.1</b> Basic data handling</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-handling.html"><a href="data-handling.html#creating-objects"><i class="fa fa-check"></i><b>3.1.1</b> Creating objects</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-handling.html"><a href="data-handling.html#data-types"><i class="fa fa-check"></i><b>3.1.2</b> Data types</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-handling.html"><a href="data-handling.html#data-structures"><i class="fa fa-check"></i><b>3.1.3</b> Data structures</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-handling.html"><a href="data-handling.html#data-import-and-export"><i class="fa fa-check"></i><b>3.2</b> Data import and export</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-handling.html"><a href="data-handling.html#getting-data-for-this-course"><i class="fa fa-check"></i><b>3.2.1</b> Getting data for this course</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-handling.html"><a href="data-handling.html#import-data-created-by-other-software-packages"><i class="fa fa-check"></i><b>3.2.2</b> Import data created by other software packages</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-handling.html"><a href="data-handling.html#import-data-from-qualtrics"><i class="fa fa-check"></i><b>3.2.3</b> Import data from Qualtrics</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-handling.html"><a href="data-handling.html#export-data"><i class="fa fa-check"></i><b>3.2.4</b> Export data</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-handling.html"><a href="data-handling.html#import-data-from-the-web"><i class="fa fa-check"></i><b>3.2.5</b> Import data from the Web</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-handling.html"><a href="data-handling.html#learning-check-1"><i class="fa fa-check"></i>Learning check</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="summarizing-data.html"><a href="summarizing-data.html"><i class="fa fa-check"></i><b>4</b> Summarizing data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="summarizing-data.html"><a href="summarizing-data.html#summary-statistics"><i class="fa fa-check"></i><b>4.1</b> Summary statistics</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables"><i class="fa fa-check"></i><b>4.1.1</b> Categorical variables</a></li>
<li class="chapter" data-level="4.1.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables"><i class="fa fa-check"></i><b>4.1.2</b> Continuous variables</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="summarizing-data.html"><a href="summarizing-data.html#data-visualization"><i class="fa fa-check"></i><b>4.2</b> Data visualization</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables-1"><i class="fa fa-check"></i><b>4.2.1</b> Categorical variables</a></li>
<li class="chapter" data-level="4.2.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables-1"><i class="fa fa-check"></i><b>4.2.2</b> Continuous variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="summarizing-data.html"><a href="summarizing-data.html#saving-plots"><i class="fa fa-check"></i><b>4.2.3</b> Saving plots</a></li>
<li class="chapter" data-level="4.2.4" data-path="summarizing-data.html"><a href="summarizing-data.html#ggplot-extensions"><i class="fa fa-check"></i><b>4.2.4</b> ggplot extensions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="summarizing-data.html"><a href="summarizing-data.html#learning-check-2"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="summarizing-data.html"><a href="summarizing-data.html#references-1"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>5</b> Statistical inference</a>
<ul>
<li class="chapter" data-level="5.1" data-path="statistical-inference.html"><a href="statistical-inference.html#if-we-knew-it-all"><i class="fa fa-check"></i><b>5.1</b> If we knew it all</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="statistical-inference.html"><a href="statistical-inference.html#sampling-from-a-known-population"><i class="fa fa-check"></i><b>5.1.1</b> Sampling from a known population</a></li>
<li class="chapter" data-level="5.1.2" data-path="statistical-inference.html"><a href="statistical-inference.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>5.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="statistical-inference.html"><a href="statistical-inference.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>5.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="5.3" data-path="statistical-inference.html"><a href="statistical-inference.html#using-what-we-actually-know"><i class="fa fa-check"></i><b>5.3</b> Using what we actually know</a></li>
<li class="chapter" data-level="5.4" data-path="statistical-inference.html"><a href="statistical-inference.html#confidence-intervals-for-the-sample-mean"><i class="fa fa-check"></i><b>5.4</b> Confidence Intervals for the Sample Mean</a></li>
<li class="chapter" data-level="" data-path="statistical-inference.html"><a href="statistical-inference.html#learning-check-3"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="statistical-inference.html"><a href="statistical-inference.html#references-2"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>6</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-1"><i class="fa fa-check"></i><b>6.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#the-null-hypothesis"><i class="fa fa-check"></i><b>6.1.1</b> The null hypothesis</a></li>
<li class="chapter" data-level="6.1.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-inference-on-a-sample"><i class="fa fa-check"></i><b>6.1.2</b> Statistical inference on a sample</a></li>
<li class="chapter" data-level="6.1.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#choosing-the-right-test"><i class="fa fa-check"></i><b>6.1.3</b> Choosing the right test</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>6.2</b> One sample t-test</a></li>
<li class="chapter" data-level="6.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-two-means"><i class="fa fa-check"></i><b>6.3</b> Comparing two means</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#independent-means-t-test"><i class="fa fa-check"></i><b>6.3.1</b> Independent-means t-test</a></li>
<li class="chapter" data-level="6.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#dependent-means-t-test"><i class="fa fa-check"></i><b>6.3.2</b> Dependent-means t-test</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#nhst-considerations"><i class="fa fa-check"></i><b>6.4</b> NHST considerations</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i><b>6.4.1</b> Type I and Type II Errors</a></li>
<li class="chapter" data-level="6.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#significance-level-sample-size-power-and-effect-size"><i class="fa fa-check"></i><b>6.4.2</b> Significance level, sample size, power, and effect size</a></li>
<li class="chapter" data-level="6.4.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#p-values-stopping-rules-and-p-hacking"><i class="fa fa-check"></i><b>6.4.3</b> P-values, stopping rules and p-hacking</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-several-means"><i class="fa fa-check"></i><b>6.5</b> Comparing several means</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-2"><i class="fa fa-check"></i><b>6.5.1</b> Introduction</a></li>
<li class="chapter" data-level="6.5.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#decomposing-variance"><i class="fa fa-check"></i><b>6.5.2</b> Decomposing variance</a></li>
<li class="chapter" data-level="6.5.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-way-anova"><i class="fa fa-check"></i><b>6.5.3</b> One-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#non-parametric-tests"><i class="fa fa-check"></i><b>6.6</b> Non-parametric tests</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#mann-whitney-u-test-a.k.a.-wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>6.6.1</b> Mann-Whitney U Test (a.k.a. Wilcoxon rank-sum test)</a></li>
<li class="chapter" data-level="6.6.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>6.6.2</b> Wilcoxon signed-rank test</a></li>
<li class="chapter" data-level="6.6.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#kruskal-wallis-test"><i class="fa fa-check"></i><b>6.6.3</b> Kruskal-Wallis test</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#categorical-data"><i class="fa fa-check"></i><b>6.7</b> Categorical data</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#confidence-intervals-for-proportions"><i class="fa fa-check"></i><b>6.7.1</b> Confidence intervals for proportions</a></li>
<li class="chapter" data-level="6.7.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#chi-square-test"><i class="fa fa-check"></i><b>6.7.2</b> Chi-square test</a></li>
<li class="chapter" data-level="6.7.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#sample-size-1"><i class="fa fa-check"></i><b>6.7.3</b> Sample size</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#learning-check-4"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#references-3"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>7</b> Regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="regression.html"><a href="regression.html#correlation"><i class="fa fa-check"></i><b>7.1</b> Correlation</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="regression.html"><a href="regression.html#correlation-coefficient"><i class="fa fa-check"></i><b>7.1.1</b> Correlation coefficient</a></li>
<li class="chapter" data-level="7.1.2" data-path="regression.html"><a href="regression.html#significance-testing"><i class="fa fa-check"></i><b>7.1.2</b> Significance testing</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="regression.html"><a href="regression.html#regression-1"><i class="fa fa-check"></i><b>7.2</b> Regression</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="regression.html"><a href="regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>7.2.1</b> Simple linear regression</a></li>
<li class="chapter" data-level="7.2.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>7.2.2</b> Multiple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="regression.html"><a href="regression.html#potential-problems"><i class="fa fa-check"></i><b>7.3</b> Potential problems</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="regression.html"><a href="regression.html#outliers"><i class="fa fa-check"></i><b>7.3.1</b> Outliers</a></li>
<li class="chapter" data-level="7.3.2" data-path="regression.html"><a href="regression.html#influential-observations"><i class="fa fa-check"></i><b>7.3.2</b> Influential observations</a></li>
<li class="chapter" data-level="7.3.3" data-path="regression.html"><a href="regression.html#non-linearity"><i class="fa fa-check"></i><b>7.3.3</b> Non-linearity</a></li>
<li class="chapter" data-level="7.3.4" data-path="regression.html"><a href="regression.html#non-constant-error-variance"><i class="fa fa-check"></i><b>7.3.4</b> Non-constant error variance</a></li>
<li class="chapter" data-level="7.3.5" data-path="regression.html"><a href="regression.html#non-normally-distributed-errors"><i class="fa fa-check"></i><b>7.3.5</b> Non-normally distributed errors</a></li>
<li class="chapter" data-level="7.3.6" data-path="regression.html"><a href="regression.html#correlation-of-errors"><i class="fa fa-check"></i><b>7.3.6</b> Correlation of errors</a></li>
<li class="chapter" data-level="7.3.7" data-path="regression.html"><a href="regression.html#collinearity"><i class="fa fa-check"></i><b>7.3.7</b> Collinearity</a></li>
<li class="chapter" data-level="7.3.8" data-path="regression.html"><a href="regression.html#omitted-variables"><i class="fa fa-check"></i><b>7.3.8</b> Omitted Variables</a></li>
<li class="chapter" data-level="7.3.9" data-path="regression.html"><a href="regression.html#overfitting"><i class="fa fa-check"></i><b>7.3.9</b> Overfitting</a></li>
<li class="chapter" data-level="7.3.10" data-path="regression.html"><a href="regression.html#variable-selection"><i class="fa fa-check"></i><b>7.3.10</b> Variable selection</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="regression.html"><a href="regression.html#categorical-predictors"><i class="fa fa-check"></i><b>7.4</b> Categorical predictors</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="regression.html"><a href="regression.html#two-categories"><i class="fa fa-check"></i><b>7.4.1</b> Two categories</a></li>
<li class="chapter" data-level="7.4.2" data-path="regression.html"><a href="regression.html#more-than-two-categories"><i class="fa fa-check"></i><b>7.4.2</b> More than two categories</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="regression.html"><a href="regression.html#extensions-of-the-linear-model"><i class="fa fa-check"></i><b>7.5</b> Extensions of the linear model</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="regression.html"><a href="regression.html#interaction-effects"><i class="fa fa-check"></i><b>7.5.1</b> Interaction effects</a></li>
<li class="chapter" data-level="7.5.2" data-path="regression.html"><a href="regression.html#non-linear-relationships"><i class="fa fa-check"></i><b>7.5.2</b> Non-linear relationships</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="regression.html"><a href="regression.html#logistic-regression"><i class="fa fa-check"></i><b>7.6</b> Logistic regression</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="regression.html"><a href="regression.html#motivation-and-intuition"><i class="fa fa-check"></i><b>7.6.1</b> Motivation and intuition</a></li>
<li class="chapter" data-level="7.6.2" data-path="regression.html"><a href="regression.html#technical-details-of-the-model"><i class="fa fa-check"></i><b>7.6.2</b> Technical details of the model</a></li>
<li class="chapter" data-level="7.6.3" data-path="regression.html"><a href="regression.html#estimation-in-r"><i class="fa fa-check"></i><b>7.6.3</b> Estimation in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#learning-check-5"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#references-4"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html"><i class="fa fa-check"></i><b>8</b> Exploratory factor analysis</a>
<ul>
<li class="chapter" data-level="8.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#introduction-3"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#steps-in-factor-analysis"><i class="fa fa-check"></i><b>8.2</b> Steps in factor analysis</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#are-the-assumptions-satisfied"><i class="fa fa-check"></i><b>8.2.1</b> Are the assumptions satisfied?</a></li>
<li class="chapter" data-level="8.2.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#deriving-factors"><i class="fa fa-check"></i><b>8.2.2</b> Deriving factors</a></li>
<li class="chapter" data-level="8.2.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#factor-interpretation"><i class="fa fa-check"></i><b>8.2.3</b> Factor interpretation</a></li>
<li class="chapter" data-level="8.2.4" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#creating-new-variables"><i class="fa fa-check"></i><b>8.2.4</b> Creating new variables</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#reliability-analysis"><i class="fa fa-check"></i><b>8.3</b> Reliability analysis</a></li>
<li class="chapter" data-level="" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#learning-check-6"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#references-5"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="cluster-analysis.html"><a href="cluster-analysis.html"><i class="fa fa-check"></i><b>9</b> Cluster analysis</a>
<ul>
<li class="chapter" data-level="9.1" data-path="cluster-analysis.html"><a href="cluster-analysis.html#k-means"><i class="fa fa-check"></i><b>9.1</b> K-Means</a></li>
<li class="chapter" data-level="9.2" data-path="cluster-analysis.html"><a href="cluster-analysis.html#hierarchical-clustering"><i class="fa fa-check"></i><b>9.2</b> Hierarchical Clustering</a></li>
</ul></li>
<li class="part"><span><b>III Assignments</b></span></li>
<li class="chapter" data-level="10" data-path="r-markdown.html"><a href="r-markdown.html"><i class="fa fa-check"></i><b>10</b> R Markdown</a>
<ul>
<li class="chapter" data-level="10.1" data-path="r-markdown.html"><a href="r-markdown.html#introduction-to-r-markdown"><i class="fa fa-check"></i><b>10.1</b> Introduction to R Markdown</a>
<ul>
<li class="chapter" data-level="" data-path="r-markdown.html"><a href="r-markdown.html#creating-a-new-r-markdown-document"><i class="fa fa-check"></i>Creating a new R Markdown document</a></li>
<li class="chapter" data-level="" data-path="r-markdown.html"><a href="r-markdown.html#text-and-equations"><i class="fa fa-check"></i>Text and Equations</a></li>
<li class="chapter" data-level="" data-path="r-markdown.html"><a href="r-markdown.html#r-code"><i class="fa fa-check"></i>R-Code</a></li>
<li class="chapter" data-level="" data-path="r-markdown.html"><a href="r-markdown.html#latex-math"><i class="fa fa-check"></i>LaTeX Math</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="r-markdown.html"><a href="r-markdown.html#assignment-1-solution"><i class="fa fa-check"></i><b>10.2</b> Assignment 1: Solution</a></li>
</ul></li>
<li class="part"><span><b>IV Group project</b></span></li>
<li class="chapter" data-level="11" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html"><i class="fa fa-check"></i><b>11</b> Survey design &amp; analysis</a>
<ul>
<li class="chapter" data-level="11.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#your-tasks"><i class="fa fa-check"></i><b>11.1</b> Your tasks</a></li>
<li class="chapter" data-level="11.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#topics-for-the-group-project"><i class="fa fa-check"></i><b>11.2</b> Topics for the group project</a></li>
<li class="chapter" data-level="11.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#general-information"><i class="fa fa-check"></i><b>11.3</b> General information</a></li>
<li class="chapter" data-level="11.4" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#part-1-questionnaire-design"><i class="fa fa-check"></i><b>11.4</b> Part 1: Questionnaire design</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#guidelines-for-the-submission-and-presentation"><i class="fa fa-check"></i><b>11.4.1</b> Guidelines for the submission and presentation</a></li>
<li class="chapter" data-level="11.4.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#guidelines-for-the-design-of-your-questionnaire"><i class="fa fa-check"></i><b>11.4.2</b> Guidelines for the design of your questionnaire</a></li>
<li class="chapter" data-level="11.4.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#questionnaire-structure-and-contents"><i class="fa fa-check"></i><b>11.4.3</b> Questionnaire structure and contents</a></li>
<li class="chapter" data-level="11.4.4" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#test-your-questionnaire"><i class="fa fa-check"></i><b>11.4.4</b> Test your questionnaire</a></li>
<li class="chapter" data-level="11.4.5" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#data-collection"><i class="fa fa-check"></i><b>11.4.5</b> Data collection</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#part-2-data-analysis"><i class="fa fa-check"></i><b>11.5</b> Part 2: Data analysis</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#guidelines-for-the-submission-and-presentation-1"><i class="fa fa-check"></i><b>11.5.1</b> Guidelines for the submission and presentation</a></li>
<li class="chapter" data-level="11.5.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#data-export-from-qualtrics"><i class="fa fa-check"></i><b>11.5.2</b> Data export from Qualtrics</a></li>
<li class="chapter" data-level="11.5.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#randomized-groups"><i class="fa fa-check"></i><b>11.5.3</b> Randomized groups</a></li>
<li class="chapter" data-level="11.5.4" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#importing-qualtrics-data"><i class="fa fa-check"></i><b>11.5.4</b> Importing Qualtrics data</a></li>
<li class="chapter" data-level="11.5.5" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#data-handling-1"><i class="fa fa-check"></i><b>11.5.5</b> Data handling</a></li>
<li class="chapter" data-level="11.5.6" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#visualizations"><i class="fa fa-check"></i><b>11.5.6</b> Visualizations</a></li>
<li class="chapter" data-level="11.5.7" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#working-with-factors"><i class="fa fa-check"></i><b>11.5.7</b> Working with factors</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V FAQ</b></span></li>
<li class="chapter" data-level="12" data-path="faq.html"><a href="faq.html"><i class="fa fa-check"></i><b>12</b> FAQ</a>
<ul>
<li class="chapter" data-level="12.1" data-path="faq.html"><a href="faq.html#common-error-messages"><i class="fa fa-check"></i><b>12.1</b> Common error messages</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#a-general-note-on-error-messages"><i class="fa fa-check"></i>A general note on error messages</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-filefile-rt-cannot-open-the-connection"><i class="fa fa-check"></i>Error in file(file, “rt”): cannot open the connection</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-unexpected-symbol-in-call"><i class="fa fa-check"></i>Error: unexpected ‘SYMBOL’ in “CALL”</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-call-object-of-type-closure-is-not-subsettable"><i class="fa fa-check"></i>Error in CALL : object of type ‘closure’ is not subsettable</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-call_with_-operator-is-invalid-for-atomic-vectors"><i class="fa fa-check"></i>Error in CALL_WITH_$: $ operator is invalid for atomic vectors</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-call-object-name-not-found"><i class="fa fa-check"></i>Error in CALL: object ‘NAME’ not found</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-call-could-not-find-function-function"><i class="fa fa-check"></i>Error in CALL: could not find function “FUNCTION”</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#error-in-call-incorrect-number-of-dimension"><i class="fa fa-check"></i>Error in CALL: incorrect number of dimension</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="faq.html"><a href="faq.html#installation-of-r-packages"><i class="fa fa-check"></i><b>12.2</b> Installation of R packages</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#what-are-the-different-ways-to-install-r-packages"><i class="fa fa-check"></i>What are the different ways to install R packages?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#i-cannot-install-packages-due-to-error-in-contrib.urlrepossource-or-warning-message-package-packagename-is-not-available-for-this-version-of-r"><i class="fa fa-check"></i>I cannot install packages due to “Error in contrib.url(repos,”source”)” or “Warning message: package ‘PACKAGENAME’ is not available for this version of R”</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#some-libraries-with-graphical-output-e.g.-summarytools-magick-fail-to-installload-properly-on-macos"><i class="fa fa-check"></i>Some libraries with graphical output (e.g., summarytools, magick) fail to install/load properly on MacOS</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#i-cannot-install-some-packages-on-macos"><i class="fa fa-check"></i>I cannot install some packages on MacOS</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="faq.html"><a href="faq.html#issues-with-statistics-and-data"><i class="fa fa-check"></i><b>12.3</b> Issues with statistics and data</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#why-does-a-multi-item-scale-lead-to-increased-reliability"><i class="fa fa-check"></i>Why does a multi-item scale lead to increased reliability?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#why-can-demeaningstandardization-lead-to-missing-values"><i class="fa fa-check"></i>Why can demeaning/standardization lead to missing values?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#the-confidence-interval-ci-of-the-mean-seems-very-small-compared-to-the-dispersion-of-my-sample.-can-this-be-correct"><i class="fa fa-check"></i>The confidence interval (CI) of the mean seems very small compared to the dispersion of my sample. Can this be correct?</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="faq.html"><a href="faq.html#errors-related-to-specific-methods"><i class="fa fa-check"></i><b>12.4</b> Errors related to specific methods</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#logistic-regression-1"><i class="fa fa-check"></i>Logistic regression</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#when-using-logistic-regression-error-in-weights-y-non-numeric-argument-to-binary-operator"><i class="fa fa-check"></i>When using logistic regression: Error in weights * y : non-numeric argument to binary operator</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="faq.html"><a href="faq.html#general-settings-and-options"><i class="fa fa-check"></i><b>12.5</b> General settings and options</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#numbers-are-formatted-weirdly"><i class="fa fa-check"></i>Numbers are formatted weirdly</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="faq.html"><a href="faq.html#data-visualizationoutput-issues"><i class="fa fa-check"></i><b>12.6</b> Data visualization/output issues</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#how-can-the-geom-colors-in-a-ggplot-be-changed"><i class="fa fa-check"></i>How can the <code>geom</code> colors in a <code>ggplot</code> be changed?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#why-are-some-histograms-displayed-differently"><i class="fa fa-check"></i>Why are some histograms displayed differently?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#some-labels-in-plots-are-cut-off.-how-can-i-extend-the-plot-margins"><i class="fa fa-check"></i>Some labels in plots are cut off. How can I extend the plot margins?</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="faq.html"><a href="faq.html#issues-with-functions-and-function-arguments"><i class="fa fa-check"></i><b>12.7</b> Issues with functions and function arguments</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#problems-with-factor-and-as.factor"><i class="fa fa-check"></i>Problems with <code>factor</code> and <code>as.factor</code></a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#how-can-i-find-an-explanation-of-the-output-of-a-function"><i class="fa fa-check"></i>How can I find an explanation of the output of a function?</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#what-does-the-margin-argument-do"><i class="fa fa-check"></i>What does the <code>MARGIN</code> argument do?</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="faq.html"><a href="faq.html#issues-with-r-markdown"><i class="fa fa-check"></i><b>12.8</b> Issues with R Markdown</a>
<ul>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#i-get-an-error-when-knitting-to-pdf-but-it-works-for-html"><i class="fa fa-check"></i>I get an error when <code>knit</code>ting to PDF but it works for HTML</a></li>
<li class="chapter" data-level="" data-path="faq.html"><a href="faq.html#i-am-not-sure-where-r-code-latex-math-and-text-go"><i class="fa fa-check"></i>I am not sure where R-code, LaTeX math, and text go</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="faq.html"><a href="faq.html#new-questions"><i class="fa fa-check"></i><b>12.9</b> New questions</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Marketing Analytics 2022</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="r-markdown" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">10</span> R Markdown<a href="r-markdown.html#r-markdown" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-to-r-markdown" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Introduction to R Markdown<a href="r-markdown.html#introduction-to-r-markdown" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="infobox download">
<p><a href="./Code/rmarkdown_example.Rmd">You can download the example markdown file here</a></p>
</div>
<p>This page will guide you through creating and editing R Markdown documents. This is a useful tool for reporting your analysis (e.g. for homework assignments). Of course, there is also <a href="https://www.rstudio.org/links/r_markdown_cheat_sheet">a cheat sheet for R-Markdown</a> and <a href="https://bookdown.org/yihui/rmarkdown/">this book</a> contains a comprehensive discussion of the format.</p>
<p>The following video contains a short introduction to the R Markdown format.</p>
<br>
<div align="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/o8FdyMAR-g4" frameborder="0" allowfullscreen>
</iframe>
</div>
<p><br></p>
<div id="creating-a-new-r-markdown-document" class="section level3 unnumbered hasAnchor">
<h3>Creating a new R Markdown document<a href="r-markdown.html#creating-a-new-r-markdown-document" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In addition to the video, the following text contains a short description of the most important formatting options.</p>
<p>Let’s start to go through the steps of creating and .Rmd file and outputting the content to an HTML file.</p>
<ol start="0" style="list-style-type: decimal">
<li><p>If an R-Markdown file was provided to you, open it with R-Studio and skip to <a href="#step4">step 4</a> after adding your answers.</p></li>
<li><p>Open R-Studio</p></li>
<li><p>Create a new R-Markdown document
<img src="rmdExplain/start.PNG" />
<img src="rmdExplain/openDoc.PNG" />
<img src="rmdExplain/enterName.PNG" />
<img src="rmdExplain/template.PNG" /></p></li>
<li><p>Save with appropriate name
<img src="rmdExplain/saving.PNG" /></p>
<p>3.1. Add your answers</p>
<p>3.2. Save again</p></li>
</ol>
<p><a name="step4"></a></p>
<ol start="4" style="list-style-type: decimal">
<li><p>“Knit” to HTML
<img src="rmdExplain/knit.PNG" /></p></li>
<li><p>Hand in appropriate file (ending in <code>.html</code>) on learn@WU
<img src="rmdExplain/handin.PNG" /></p></li>
</ol>
</div>
<div id="text-and-equations" class="section level3 unnumbered hasAnchor">
<h3>Text and Equations<a href="r-markdown.html#text-and-equations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>R-Markdown documents are plain text files that include both text and R-code. Using RStudio they can be converted (‘knitted’) to HTML or PDF files that include both the text and the results of the R-code. In fact this website is written using R-Markdown and RStudio. In order for RStudio to be able to interpret the document you have to use certain characters or combinations of characters when formatting text and including R-code to be evaluated. By default the document starts with the options for the text part. You can change the title, date, author and a few more advanced options.</p>
<div class="figure">
<img src="rmdExplain/rmdHead.PNG" alt="" />
<p class="caption">First lines of an R-Markdown document</p>
</div>
<p>The default is text mode, meaning that lines in an Rmd document will be interpreted as text, unless specified otherwise.</p>
<div id="headings" class="section level4 unnumbered hasAnchor">
<h4>Headings<a href="r-markdown.html#headings" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Usually you want to include some kind of heading to structure your text. A heading is created using <code>#</code> signs. A single <code>#</code> creates a first level heading, two <code>##</code> a second level and so on.</p>
<p><img src="rmdExplain/headings.PNG" /></p>
<p>It is important to note here that the <code>#</code> symbol means something different within the code chunks as opposed to outside of them. If you continue to put a <code>#</code> in front of all your regular text, it will all be interpreted as a first level heading, making your text very large.</p>
</div>
<div id="lists" class="section level4 unnumbered hasAnchor">
<h4>Lists<a href="r-markdown.html#lists" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Bullet point lists are created using <code>*</code>, <code>+</code> or <code>-</code>. Sub-items are created by indenting the item using 4 spaces or 2 tabs.</p>
<pre><code>* First Item
* Second Item
    + first sub-item
        - first sub-sub-item
    + second sub-item</code></pre>
<ul>
<li>First Item</li>
<li>Second Item
<ul>
<li>first sub-item
<ul>
<li>first sub-sub-item</li>
</ul></li>
<li>second sub-item</li>
</ul></li>
</ul>
<p>Ordered lists can be created using numbers and letters. If you need sub-sub-items use <code>A)</code> instead of <code>A.</code> on the third level.</p>
<pre><code>1. First item
    a. first sub-item
        A) first sub-sub-item 
     b. second sub-item
2. Second item</code></pre>
<ol style="list-style-type: decimal">
<li>First item
<ol style="list-style-type: lower-alpha">
<li>first sub-item
<ol style="list-style-type: upper-alpha">
<li>first sub-sub-item</li>
</ol></li>
<li>second sub-item</li>
</ol></li>
<li>Second item</li>
</ol>
</div>
<div id="text-formatting" class="section level4 unnumbered hasAnchor">
<h4>Text formatting<a href="r-markdown.html#text-formatting" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Text can be formatted in <em>italics</em> (<code>*italics*</code>) or <strong>bold</strong> (<code>**bold**</code>). In addition, you can ad block quotes with <code>&gt;</code></p>
<pre><code>&gt; Lorem ipsum dolor amet chillwave lomo ramps, four loko green juice messenger bag raclette forage offal shoreditch chartreuse austin. Slow-carb poutine meggings swag blog, pop-up salvia taxidermy bushwick freegan ugh poke.</code></pre>
<blockquote>
<p>Lorem ipsum dolor amet chillwave lomo ramps, four loko green juice messenger bag raclette forage offal shoreditch chartreuse austin. Slow-carb poutine meggings swag blog, pop-up salvia taxidermy bushwick freegan ugh poke.</p>
</blockquote>
</div>
</div>
<div id="r-code" class="section level3 unnumbered hasAnchor">
<h3>R-Code<a href="r-markdown.html#r-code" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>R-code is contained in so called “chunks”. These chunks always start with three backticks and <code>r</code> in curly braces (<code></code>{r} <code>) and end with three backticks (</code> <code></code>). Optionally, parameters can be added after the <code>r</code> to influence how a chunk behaves. Additionally, you can also give each chunk a name. Note that these have to be <strong>unique</strong>, otherwise R will refuse to knit your document.</p>
<div id="global-and-chunk-options" class="section level4 unnumbered hasAnchor">
<h4>Global and chunk options<a href="r-markdown.html#global-and-chunk-options" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The first chunk always looks as follows</p>
<pre><code>```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```</code></pre>
<p>It is added to the document automatically and sets options for all the following chunks. These options can be overwritten on a per-chunk basis.</p>
<p>Keep <code>knitr::opts_chunk$set(echo = TRUE)</code> to print your code to the document you will hand in. Changing it to <code>knitr::opts_chunk$set(echo = FALSE)</code> will not print your code by default. This can be changed on a per-chunk basis.</p>
<pre><code>```{r cars, echo = FALSE}
summary(cars)

plot(dist~speed, cars)
```</code></pre>
<pre><code>##      speed           dist       
##  Min.   : 4.0   Min.   :  2.00  
##  1st Qu.:12.0   1st Qu.: 26.00  
##  Median :15.0   Median : 36.00  
##  Mean   :15.4   Mean   : 42.98  
##  3rd Qu.:19.0   3rd Qu.: 56.00  
##  Max.   :25.0   Max.   :120.00</code></pre>
<p><img src="14-rmdIntro_files/figure-html/cars-1.png" width="672" /></p>
<pre><code>```{r cars2, echo = TRUE}
summary(cars)

plot(dist~speed, cars)
```</code></pre>
<div class="sourceCode" id="cb757"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb757-1"><a href="r-markdown.html#cb757-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cars)</span></code></pre></div>
<pre><code>##      speed           dist       
##  Min.   : 4.0   Min.   :  2.00  
##  1st Qu.:12.0   1st Qu.: 26.00  
##  Median :15.0   Median : 36.00  
##  Mean   :15.4   Mean   : 42.98  
##  3rd Qu.:19.0   3rd Qu.: 56.00  
##  Max.   :25.0   Max.   :120.00</code></pre>
<div class="sourceCode" id="cb759"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb759-1"><a href="r-markdown.html#cb759-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dist <span class="sc">~</span> speed, cars)</span></code></pre></div>
<p><img src="14-rmdIntro_files/figure-html/cars2-1.png" width="672" /></p>
<p>A good overview of all available global/chunk options can be found <a href="https://yihui.name/knitr/options/#chunk_options">here</a>.</p>
</div>
</div>
<div id="latex-math" class="section level3 unnumbered hasAnchor">
<h3>LaTeX Math<a href="r-markdown.html#latex-math" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Writing well formatted mathematical formulas is done the same way as in <a href="https://en.wikipedia.org/wiki/LaTeX">LaTeX</a>. Math mode is started and ended using <code>$$</code>.</p>
<pre><code>$$
 f_1(\omega) = \frac{\sigma^2}{2 \pi},\ \omega \in[-\pi, \pi]
$$</code></pre>
<p><span class="math display">\[
f_1(\omega) = \frac{\sigma^2}{2 \pi},\ \omega \in[-\pi, \pi]
\]</span></p>
<p>(for those interested this is the spectral density of <a href="https://en.wikipedia.org/wiki/White_noise">white noise</a>)</p>
<p>Including inline mathematical notation is done with a single <code>$</code> symbol.</p>
<pre><code>${2\over3}$ of my code is inline.
</code></pre>
<p><span class="math inline">\({2\over3}\)</span> of my code is inline.</p>
<p><br></p>
<p>Take a look at <a href="https://en.wikibooks.org/wiki/LaTeX/Mathematics#Symbols">this wikibook on Mathematics in LaTeX</a> and <a href="https://www.sharelatex.com/learn/List_of_Greek_letters_and_math_symbols">this list of Greek letters and mathematical symbols</a> if you are not familiar with LaTeX.</p>
<p>In order to write multi-line equations in the same math environment, use <code>\\</code> after every line. In order to insert a space use a single <code>\</code>. To render text inside a math environment use <code>\text{here is the text}</code>. In order to align equations start with <code>\begin{align}</code> and place an <code>&amp;</code> in each line at the point around which it should be aligned. Finally end with <code>\end{align}</code></p>
<pre><code>$$
\begin{align}
\text{First equation: }\ Y &amp;= X \beta + \epsilon_y,\ \forall X \\
\text{Second equation: }\ X &amp;= Z \gamma + \epsilon_x
\end{align}
$$</code></pre>
<p><span class="math display">\[
\begin{align}
\text{First equation: }\ Y &amp;= X \beta + \epsilon_y,\ \forall X \\
\text{Second equation: }\ X &amp;= Z \gamma + \epsilon_x
\end{align}
\]</span></p>
<div id="important-symbols" class="section level4 unnumbered hasAnchor">
<h4>Important symbols<a href="r-markdown.html#important-symbols" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Symbol
</th>
<th style="text-align:left;">
Code
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a^{2} + b\)</span>
</td>
<td style="text-align:left;">
<code>a^{2} + b</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a^{2+b}\)</span>
</td>
<td style="text-align:left;">
<code>a^{2+b}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a_{1}\)</span>
</td>
<td style="text-align:left;">
<code>a_{1}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \leq b\)</span>
</td>
<td style="text-align:left;">
<code>a \leq b</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \geq b\)</span>
</td>
<td style="text-align:left;">
<code>a \geq b</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \neq b\)</span>
</td>
<td style="text-align:left;">
<code>a \neq b</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \approx b\)</span>
</td>
<td style="text-align:left;">
<code>a \approx b</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \in (0,1)\)</span>
</td>
<td style="text-align:left;">
<code>a \in (0,1)</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \rightarrow \infty\)</span>
</td>
<td style="text-align:left;">
<code>a \rightarrow \infty</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\frac{a}{b}\)</span>
</td>
<td style="text-align:left;">
<code>\frac{a}{b}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\frac{\partial a}{\partial b}\)</span>
</td>
<td style="text-align:left;">
<code>\frac{\partial a}{\partial b}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sqrt{a}\)</span>
</td>
<td style="text-align:left;">
<code>\sqrt{a}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sum_{i = 1}^{b} a_i\)</span>
</td>
<td style="text-align:left;">
<code>\sum_{i = 1}^{b} a_i</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\int_{a}^b f(c) dc\)</span>
</td>
<td style="text-align:left;">
<code>\int_{a}^b f(c) dc</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\prod_{i = 0}^b a_i\)</span>
</td>
<td style="text-align:left;">
<code>\prod_{i = 0}^b a_i</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(c \left( \sum_{i=1}^b a_i \right)\)</span>
</td>
<td style="text-align:left;">
<code>c \left( \sum_{i=1}^b a_i \right)</code>
</td>
</tr>
</tbody>
</table>
<p>The <code>{}</code> after <code>_</code> and <code>^</code> are not strictly necessary if there is only one character in the sub-/superscript. However, in order to place multiple characters in the sub-/superscript they are necessary.
e.g.</p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Symbol
</th>
<th style="text-align:left;">
Code
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a^b = a^{b}\)</span>
</td>
<td style="text-align:left;">
<code>a^b = a^{b}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a^b+c \neq a^{b+c}\)</span>
</td>
<td style="text-align:left;">
<code>a^b+c \neq a^{b+c}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sum_i a_i = \sum_{i} a_{i}\)</span>
</td>
<td style="text-align:left;">
<code>\sum_i a_i = \sum_{i} a_{i}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sum_{i=1}^{b+c} a_i \neq \sum_i=1^b+c a_i\)</span>
</td>
<td style="text-align:left;">
<code>\sum_{i=1}^{b+c} a_i \neq \sum_i=1^b+c a_i</code>
</td>
</tr>
</tbody>
</table>
</div>
<div id="greek-letters" class="section level4 unnumbered hasAnchor">
<h4>Greek letters<a href="r-markdown.html#greek-letters" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><a href="https://en.wikipedia.org/wiki/Greek_alphabet#Letters">Greek letters</a> are preceded by a <code>\</code> followed by their name (<code>$\beta$</code> = <span class="math inline">\(\beta\)</span>). In order to capitalize them simply capitalize the first letter of the name (<code>$\Gamma$</code> = <span class="math inline">\(\Gamma\)</span>).</p>
</div>
</div>
</div>
<div id="assignment-1-solution" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Assignment 1: Solution<a href="r-markdown.html#assignment-1-solution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Load libraries and data</strong></p>
<div class="sourceCode" id="cb763"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb763-1"><a href="r-markdown.html#cb763-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb763-2"><a href="r-markdown.html#cb763-2" aria-hidden="true" tabindex="-1"></a>music_data <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;https://short.wu.ac.at/ma22_musicdata&quot;</span>)</span>
<span id="cb763-3"><a href="r-markdown.html#cb763-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(music_data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    66796 obs. of  31 variables:
##  $ isrc                       : chr  &quot;BRRGE1603547&quot; &quot;USUM71808193&quot; &quot;ES5701800181&quot; &quot;ITRSE2000050&quot; ...
##  $ artist_id                  : int  3679 5239 776407 433730 526471 1939 210184 212546 4938 119985 ...
##  $ streams                    : num  11944813 8934097 38835 46766 2930573 ...
##  $ weeks_in_charts            : int  141 51 1 1 7 226 13 1 64 7 ...
##  $ n_regions                  : int  1 21 1 1 4 8 1 1 5 1 ...
##  $ danceability               : num  50.9 35.3 68.3 70.4 84.2 35.2 73 55.6 71.9 34.6 ...
##  $ energy                     : num  80.3 75.5 67.6 56.8 57.8 91.1 69.6 24.5 85 43.3 ...
##  $ speechiness                : num  4 73.3 14.7 26.8 13.8 7.47 35.5 3.05 3.17 6.5 ...
##  $ instrumentalness           : num  0.05 0 0 0.000253 0 0 0 0 0.02 0 ...
##  $ liveness                   : num  46.3 39 7.26 8.91 22.8 9.95 32.1 9.21 11.4 10.1 ...
##  $ valence                    : num  65.1 43.7 43.4 49.5 19 23.6 58.4 27.6 36.7 76.8 ...
##  $ tempo                      : num  166 191.2 99 91 74.5 ...
##  $ song_length                : num  3.12 3.23 3.02 3.45 3.95 ...
##  $ song_age                   : num  228.3 144.3 112.3 50.7 58.3 ...
##  $ explicit                   : int  0 0 0 0 0 0 0 0 1 0 ...
##  $ n_playlists                : int  450 768 48 6 475 20591 6 105 547 688 ...
##  $ sp_popularity              : int  51 54 32 44 52 81 44 8 59 68 ...
##  $ youtube_views              : num  1.45e+08 1.32e+07 6.12e+06 0.00 0.00 ...
##  $ tiktok_counts              : int  9740 358700 0 13 515 67300 0 0 653 3807 ...
##  $ ins_followers_artist       : int  29613108 3693566 623778 81601 11962358 1169284 1948850 39381 9751080 343 ...
##  $ monthly_listeners_artist   : int  4133393 18367363 888273 143761 15551876 16224250 2683086 1318874 4828847 3088232 ...
##  $ playlist_total_reach_artist: int  24286416 143384531 4846378 156521 90841884 80408253 7332603 24302331 8914977 8885252 ...
##  $ sp_fans_artist             : int  3308630 465412 23846 1294 380204 1651866 214001 10742 435457 1897685 ...
##  $ shazam_counts              : int  73100 588550 0 0 55482 5281161 0 0 39055 0 ...
##  $ artistName                 : chr  &quot;Luan Santana&quot; &quot;Alessia Cara&quot; &quot;Ana Guerra&quot; &quot;Claver Gold feat. Murubutu&quot; ...
##  $ trackName                  : chr  &quot;Eu, Você, O Mar e Ela&quot; &quot;Growing Pains&quot; &quot;El Remedio&quot; &quot;Ulisse&quot; ...
##  $ release_date               : chr  &quot;2016-06-20&quot; &quot;2018-06-14&quot; &quot;2018-04-26&quot; &quot;2020-03-31&quot; ...
##  $ genre                      : chr  &quot;other&quot; &quot;Pop&quot; &quot;Pop&quot; &quot;HipHop/Rap&quot; ...
##  $ label                      : chr  &quot;Independent&quot; &quot;Universal Music&quot; &quot;Universal Music&quot; &quot;Independent&quot; ...
##  $ top10                      : int  1 0 0 0 0 1 0 0 0 0 ...
##  $ expert_rating              : chr  &quot;excellent&quot; &quot;good&quot; &quot;good&quot; &quot;poor&quot; ...</code></pre>
<div class="sourceCode" id="cb765"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb765-1"><a href="r-markdown.html#cb765-1" aria-hidden="true" tabindex="-1"></a><span class="co"># head(music_data, 2)</span></span></code></pre></div>
<p>First, you should convert the variables to the correct types:</p>
<div class="sourceCode" id="cb766"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb766-1"><a href="r-markdown.html#cb766-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb766-2"><a href="r-markdown.html#cb766-2" aria-hidden="true" tabindex="-1"></a>music_data <span class="sc">%&lt;&gt;%</span> <span class="fu">mutate</span>(<span class="at">release_date =</span> <span class="fu">as.Date</span>(release_date), <span class="co"># convert to date</span></span>
<span id="cb766-3"><a href="r-markdown.html#cb766-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">explicit =</span> <span class="fu">factor</span>(explicit, <span class="at">levels =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;not explicit&quot;</span>, <span class="st">&quot;explicit&quot;</span>)), <span class="co"># convert to factor w. new labels</span></span>
<span id="cb766-4"><a href="r-markdown.html#cb766-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">label =</span> <span class="fu">as.factor</span>(label), <span class="co"># convert to factor with values as labels</span></span>
<span id="cb766-5"><a href="r-markdown.html#cb766-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">genre =</span> <span class="fu">as.factor</span>(genre),</span>
<span id="cb766-6"><a href="r-markdown.html#cb766-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">top10 =</span> <span class="fu">as.logical</span>(top10),</span>
<span id="cb766-7"><a href="r-markdown.html#cb766-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">expert_rating =</span> <span class="fu">factor</span>(expert_rating, </span>
<span id="cb766-8"><a href="r-markdown.html#cb766-8" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;poor&quot;</span>, <span class="st">&quot;fair&quot;</span>, <span class="st">&quot;good&quot;</span>, <span class="st">&quot;excellent&quot;</span>, <span class="st">&quot;masterpiece&quot;</span>), </span>
<span id="cb766-9"><a href="r-markdown.html#cb766-9" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">ordered =</span> <span class="cn">TRUE</span>))</span>
<span id="cb766-10"><a href="r-markdown.html#cb766-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(music_data, <span class="dv">2</span>)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["isrc"],"name":[1],"type":["chr"],"align":["left"]},{"label":["artist_id"],"name":[2],"type":["int"],"align":["right"]},{"label":["streams"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["weeks_in_charts"],"name":[4],"type":["int"],"align":["right"]},{"label":["n_regions"],"name":[5],"type":["int"],"align":["right"]},{"label":["danceability"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["energy"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["speechiness"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["instrumentalness"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["liveness"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["valence"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["tempo"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["song_length"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["song_age"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["explicit"],"name":[15],"type":["fct"],"align":["left"]},{"label":["n_playlists"],"name":[16],"type":["int"],"align":["right"]},{"label":["sp_popularity"],"name":[17],"type":["int"],"align":["right"]},{"label":["youtube_views"],"name":[18],"type":["dbl"],"align":["right"]},{"label":["tiktok_counts"],"name":[19],"type":["int"],"align":["right"]},{"label":["ins_followers_artist"],"name":[20],"type":["int"],"align":["right"]},{"label":["monthly_listeners_artist"],"name":[21],"type":["int"],"align":["right"]},{"label":["playlist_total_reach_artist"],"name":[22],"type":["int"],"align":["right"]},{"label":["sp_fans_artist"],"name":[23],"type":["int"],"align":["right"]},{"label":["shazam_counts"],"name":[24],"type":["int"],"align":["right"]},{"label":["artistName"],"name":[25],"type":["chr"],"align":["left"]},{"label":["trackName"],"name":[26],"type":["chr"],"align":["left"]},{"label":["release_date"],"name":[27],"type":["date"],"align":["right"]},{"label":["genre"],"name":[28],"type":["fct"],"align":["left"]},{"label":["label"],"name":[29],"type":["fct"],"align":["left"]},{"label":["top10"],"name":[30],"type":["lgl"],"align":["right"]},{"label":["expert_rating"],"name":[31],"type":["ord"],"align":["right"]}],"data":[{"1":"BRRGE1603547","2":"3679","3":"11944813","4":"141","5":"1","6":"50.9","7":"80.3","8":"4.0","9":"0.05","10":"46.3","11":"65.1","12":"166.018","13":"3.11865","14":"228.2857","15":"not explicit","16":"450","17":"51","18":"145030723","19":"9740","20":"29613108","21":"4133393","22":"24286416","23":"3308630","24":"73100","25":"Luan Santana","26":"Eu, Você, O Mar e Ela","27":"2016-06-20","28":"other","29":"Independent","30":"TRUE","31":"excellent"},{"1":"USUM71808193","2":"5239","3":"8934097","4":"51","5":"21","6":"35.3","7":"75.5","8":"73.3","9":"0.00","10":"39.0","11":"43.7","12":"191.153","13":"3.22800","14":"144.2857","15":"not explicit","16":"768","17":"54","18":"13188411","19":"358700","20":"3693566","21":"18367363","22":"143384531","23":"465412","24":"588550","25":"Alessia Cara","26":"Growing Pains","27":"2018-06-14","28":"Pop","29":"Universal Music","30":"FALSE","31":"good"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><strong>Task 1</strong></p>
<ol style="list-style-type: decimal">
<li>Determine the most popular song by the artist “Billie Eilish”.</li>
<li>Create a new <code>data.frame</code> that only contains songs by “Billie Eilish” (Bonus: Also include songs that feature both Billie Eilish and other artists, see e.g., “lovely (with Khalid)”)</li>
<li>Save the <code>data.frame</code> sorted by success (number of streams) with the most popular songs occurring first.</li>
</ol>
<p>There might be multiple ways of tackling this task. For example, you could start from question 3 and first create the complete data frame with only Billie’s songs, ordered by popularity:</p>
<div class="sourceCode" id="cb767"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb767-1"><a href="r-markdown.html#cb767-1" aria-hidden="true" tabindex="-1"></a>billie_eilish <span class="ot">&lt;-</span> music_data <span class="sc">|&gt;</span></span>
<span id="cb767-2"><a href="r-markdown.html#cb767-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(artistName <span class="sc">==</span> <span class="st">&quot;Billie Eilish&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb767-3"><a href="r-markdown.html#cb767-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(streams))  <span class="co">#arrange by number of streams (in descending order)</span></span>
<span id="cb767-4"><a href="r-markdown.html#cb767-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(billie_eilish, <span class="dv">4</span>)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["isrc"],"name":[1],"type":["chr"],"align":["left"]},{"label":["artist_id"],"name":[2],"type":["int"],"align":["right"]},{"label":["streams"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["weeks_in_charts"],"name":[4],"type":["int"],"align":["right"]},{"label":["n_regions"],"name":[5],"type":["int"],"align":["right"]},{"label":["danceability"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["energy"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["speechiness"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["instrumentalness"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["liveness"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["valence"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["tempo"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["song_length"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["song_age"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["explicit"],"name":[15],"type":["fct"],"align":["left"]},{"label":["n_playlists"],"name":[16],"type":["int"],"align":["right"]},{"label":["sp_popularity"],"name":[17],"type":["int"],"align":["right"]},{"label":["youtube_views"],"name":[18],"type":["dbl"],"align":["right"]},{"label":["tiktok_counts"],"name":[19],"type":["int"],"align":["right"]},{"label":["ins_followers_artist"],"name":[20],"type":["int"],"align":["right"]},{"label":["monthly_listeners_artist"],"name":[21],"type":["int"],"align":["right"]},{"label":["playlist_total_reach_artist"],"name":[22],"type":["int"],"align":["right"]},{"label":["sp_fans_artist"],"name":[23],"type":["int"],"align":["right"]},{"label":["shazam_counts"],"name":[24],"type":["int"],"align":["right"]},{"label":["artistName"],"name":[25],"type":["chr"],"align":["left"]},{"label":["trackName"],"name":[26],"type":["chr"],"align":["left"]},{"label":["release_date"],"name":[27],"type":["date"],"align":["right"]},{"label":["genre"],"name":[28],"type":["fct"],"align":["left"]},{"label":["label"],"name":[29],"type":["fct"],"align":["left"]},{"label":["top10"],"name":[30],"type":["lgl"],"align":["right"]},{"label":["expert_rating"],"name":[31],"type":["ord"],"align":["right"]}],"data":[{"1":"USUM71900764","2":"5596","3":"1459149566","4":"724","5":"35","6":"70.1","7":"42.5","8":"37.50","9":"13.0","10":"10.0","11":"56.2","12":"135.128","13":"3.234800","14":"103.28571","15":"not explicit","16":"10226","17":"87","18":"1070192329","19":"140000","20":"78388337","21":"47632687","22":"223834163","23":"4355854","24":"15967622","25":"Billie Eilish","26":"bad guy","27":"2019-03-28","28":"Rock","29":"Universal Music","30":"TRUE","31":"good"},{"1":"USUM71922577","2":"5596","3":"594991676","4":"491","5":"35","6":"70.4","7":"22.5","8":"9.94","9":"65.7","10":"10.6","11":"24.3","12":"120.006","13":"4.090433","14":"70.57143","15":"not explicit","16":"5459","17":"86","18":"210598263","19":"71500","20":"78388337","21":"47632687","22":"223834163","23":"4355854","24":"7180495","25":"Billie Eilish","26":"everything i wanted","27":"2019-11-13","28":"Rock","29":"Universal Music","30":"TRUE","31":"good"},{"1":"USUM71900770","2":"5596","3":"298707880","4":"382","5":"35","6":"90.5","7":"38.9","8":"33.20","9":"16.2","10":"10.6","11":"19.6","12":"120.046","13":"3.219050","14":"103.28571","15":"not explicit","16":"4261","17":"79","18":"399709135","19":"8511","20":"78388337","21":"47632687","22":"223834163","23":"4355854","24":"2755292","25":"Billie Eilish","26":"bury a friend","27":"2019-01-30","28":"Rock","29":"Universal Music","30":"TRUE","31":"good"},{"1":"USUM72021500","2":"5596","3":"269394372","4":"129","5":"35","6":"88.9","7":"34.0","8":"6.97","9":"13.0","10":"5.5","11":"71.6","12":"94.009","13":"2.905350","14":"18.42857","15":"not explicit","16":"2692","17":"91","18":"141648329","19":"3100000","20":"78388337","21":"47632687","22":"223834163","23":"4355854","24":"2185476","25":"Billie Eilish","26":"Therefore I Am","27":"2020-11-12","28":"Rock","29":"Universal Music","30":"TRUE","31":"masterpiece"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>In that data frame, you could filter out and display the most popular song, using <code>max()</code> function:</p>
<div class="sourceCode" id="cb768"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb768-1"><a href="r-markdown.html#cb768-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(billie_eilish, streams <span class="sc">==</span> <span class="fu">max</span>(streams)) <span class="sc">|&gt;</span></span>
<span id="cb768-2"><a href="r-markdown.html#cb768-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(trackName)  <span class="co">#print top-1 song</span></span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["trackName"],"name":[1],"type":["chr"],"align":["left"]}],"data":[{"1":"bad guy"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>OR, as long as this data frame is already saved with the most popular song on top, you can simply take the first element of the data frame:</p>
<div class="sourceCode" id="cb769"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb769-1"><a href="r-markdown.html#cb769-1" aria-hidden="true" tabindex="-1"></a>billie_eilish[<span class="dv">1</span>, <span class="st">&quot;trackName&quot;</span>]</span></code></pre></div>
<pre><code>## [1] &quot;bad guy&quot;</code></pre>
<p><strong>Bonus:</strong> For finding all songs featuring Billie Eilish, you could use <code>str_detect()</code> function from <code>stringr</code> package. It searches for all variables in <code>artistName</code>, containing the string “Billie Eilish”. The rest stays the same:</p>
<div class="sourceCode" id="cb771"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb771-1"><a href="r-markdown.html#cb771-1" aria-hidden="true" tabindex="-1"></a>billie_eilish_full <span class="ot">&lt;-</span> <span class="fu">filter</span>(music_data, <span class="fu">str_detect</span>(artistName, <span class="st">&quot;Billie Eilish&quot;</span>)) <span class="sc">|&gt;</span> <span class="co">#filter all Billie&#39;s appearances</span></span>
<span id="cb771-2"><a href="r-markdown.html#cb771-2" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">arrange</span>(<span class="fu">desc</span>(streams)) <span class="co">#arrange by number of streams (in descending order)</span></span>
<span id="cb771-3"><a href="r-markdown.html#cb771-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb771-4"><a href="r-markdown.html#cb771-4" aria-hidden="true" tabindex="-1"></a><span class="co">#filter(billie_eilish_full, streams == max(streams)) |&gt; select(trackName) #print the top-1 song</span></span>
<span id="cb771-5"><a href="r-markdown.html#cb771-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(billie_eilish_full, <span class="dv">3</span>) </span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["isrc"],"name":[1],"type":["chr"],"align":["left"]},{"label":["artist_id"],"name":[2],"type":["int"],"align":["right"]},{"label":["streams"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["weeks_in_charts"],"name":[4],"type":["int"],"align":["right"]},{"label":["n_regions"],"name":[5],"type":["int"],"align":["right"]},{"label":["danceability"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["energy"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["speechiness"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["instrumentalness"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["liveness"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["valence"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["tempo"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["song_length"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["song_age"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["explicit"],"name":[15],"type":["fct"],"align":["left"]},{"label":["n_playlists"],"name":[16],"type":["int"],"align":["right"]},{"label":["sp_popularity"],"name":[17],"type":["int"],"align":["right"]},{"label":["youtube_views"],"name":[18],"type":["dbl"],"align":["right"]},{"label":["tiktok_counts"],"name":[19],"type":["int"],"align":["right"]},{"label":["ins_followers_artist"],"name":[20],"type":["int"],"align":["right"]},{"label":["monthly_listeners_artist"],"name":[21],"type":["int"],"align":["right"]},{"label":["playlist_total_reach_artist"],"name":[22],"type":["int"],"align":["right"]},{"label":["sp_fans_artist"],"name":[23],"type":["int"],"align":["right"]},{"label":["shazam_counts"],"name":[24],"type":["int"],"align":["right"]},{"label":["artistName"],"name":[25],"type":["chr"],"align":["left"]},{"label":["trackName"],"name":[26],"type":["chr"],"align":["left"]},{"label":["release_date"],"name":[27],"type":["date"],"align":["right"]},{"label":["genre"],"name":[28],"type":["fct"],"align":["left"]},{"label":["label"],"name":[29],"type":["fct"],"align":["left"]},{"label":["top10"],"name":[30],"type":["lgl"],"align":["right"]},{"label":["expert_rating"],"name":[31],"type":["ord"],"align":["right"]}],"data":[{"1":"USUM71900764","2":"5596","3":"1459149566","4":"724","5":"35","6":"70.1","7":"42.5","8":"37.50","9":"13.0","10":"10.0","11":"56.2","12":"135.128","13":"3.234800","14":"103.28571","15":"not explicit","16":"10226","17":"87","18":"1070192329","19":"140000","20":"78388337","21":"47632687","22":"223834163","23":"4355854","24":"15967622","25":"Billie Eilish","26":"bad guy","27":"2019-03-28","28":"Rock","29":"Universal Music","30":"TRUE","31":"good"},{"1":"USUM71804190","2":"5596","3":"736917003","4":"906","5":"35","6":"35.1","7":"29.6","8":"3.33","9":"0.0","10":"9.5","11":"12.0","12":"115.284","13":"3.336433","14":"152.42857","15":"not explicit","16":"6074","17":"88","18":"86414365","19":"24100","20":"78388337","21":"47632687","22":"223834163","23":"4355854","24":"5983153","25":"Billie Eilish feat. Khalid","26":"lovely (with Khalid)","27":"2018-04-19","28":"Rock","29":"Universal Music","30":"TRUE","31":"good"},{"1":"USUM71922577","2":"5596","3":"594991676","4":"491","5":"35","6":"70.4","7":"22.5","8":"9.94","9":"65.7","10":"10.6","11":"24.3","12":"120.006","13":"4.090433","14":"70.57143","15":"not explicit","16":"5459","17":"86","18":"210598263","19":"71500","20":"78388337","21":"47632687","22":"223834163","23":"4355854","24":"7180495","25":"Billie Eilish","26":"everything i wanted","27":"2019-11-13","28":"Rock","29":"Universal Music","30":"TRUE","31":"good"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><strong>Task 2</strong></p>
<p>Create a new <code>data.frame</code> containing the 100 most streamed songs.</p>
<p>Here you could simply arrange the whole data set by streams and then take 100 first rows using <code>slice_head()</code>:</p>
<div class="sourceCode" id="cb772"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb772-1"><a href="r-markdown.html#cb772-1" aria-hidden="true" tabindex="-1"></a>top_100 <span class="ot">&lt;-</span> <span class="fu">arrange</span>(music_data, <span class="fu">desc</span>(streams)) <span class="sc">|&gt;</span></span>
<span id="cb772-2"><a href="r-markdown.html#cb772-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">100</span>)</span>
<span id="cb772-3"><a href="r-markdown.html#cb772-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(top_100)</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["isrc"],"name":[1],"type":["chr"],"align":["left"]},{"label":["artist_id"],"name":[2],"type":["int"],"align":["right"]},{"label":["streams"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["weeks_in_charts"],"name":[4],"type":["int"],"align":["right"]},{"label":["n_regions"],"name":[5],"type":["int"],"align":["right"]},{"label":["danceability"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["energy"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["speechiness"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["instrumentalness"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["liveness"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["valence"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["tempo"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["song_length"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["song_age"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["explicit"],"name":[15],"type":["fct"],"align":["left"]},{"label":["n_playlists"],"name":[16],"type":["int"],"align":["right"]},{"label":["sp_popularity"],"name":[17],"type":["int"],"align":["right"]},{"label":["youtube_views"],"name":[18],"type":["dbl"],"align":["right"]},{"label":["tiktok_counts"],"name":[19],"type":["int"],"align":["right"]},{"label":["ins_followers_artist"],"name":[20],"type":["int"],"align":["right"]},{"label":["monthly_listeners_artist"],"name":[21],"type":["int"],"align":["right"]},{"label":["playlist_total_reach_artist"],"name":[22],"type":["int"],"align":["right"]},{"label":["sp_fans_artist"],"name":[23],"type":["int"],"align":["right"]},{"label":["shazam_counts"],"name":[24],"type":["int"],"align":["right"]},{"label":["artistName"],"name":[25],"type":["chr"],"align":["left"]},{"label":["trackName"],"name":[26],"type":["chr"],"align":["left"]},{"label":["release_date"],"name":[27],"type":["date"],"align":["right"]},{"label":["genre"],"name":[28],"type":["fct"],"align":["left"]},{"label":["label"],"name":[29],"type":["fct"],"align":["left"]},{"label":["top10"],"name":[30],"type":["lgl"],"align":["right"]},{"label":["expert_rating"],"name":[31],"type":["ord"],"align":["right"]}],"data":[{"1":"GBAHS1600463","2":"3648","3":"2165692479","4":"1532","5":"35","6":"82.5","7":"65.2","8":"8.02","9":"0.00","10":"9.31","11":"93.1","12":"95.977","13":"3.895217","14":"211.28571","15":"not explicit","16":"28754","17":"86","18":"5225251113","19":"780900","20":"31799118","21":"54645910","22":"333851354","23":"16312741","24":"1137483","25":"Ed Sheeran","26":"Shape of You","27":"2017-01-06","28":"Pop","29":"Warner Music","30":"TRUE","31":"fair"},{"1":"QZES71982312","2":"1410939","3":"1909947000","4":"649","5":"35","6":"82.5","7":"59.3","8":"9.88","9":"0.02","10":"17.00","11":"54.0","12":"98.078","13":"3.495917","14":"97.28571","15":"not explicit","16":"11330","17":"88","18":"1527998214","19":"6700000","20":"689914","21":"23941476","22":"128533003","23":"431389","24":"38107895","25":"Tones and I","26":"Dance Monkey","27":"2019-05-09","28":"Rock","29":"Warner Music","30":"TRUE","31":"excellent"},{"1":"USUM71900764","2":"5596","3":"1459149566","4":"724","5":"35","6":"70.1","7":"42.5","8":"37.50","9":"13.00","10":"10.00","11":"56.2","12":"135.128","13":"3.234800","14":"103.28571","15":"not explicit","16":"10226","17":"87","18":"1070192329","19":"140000","20":"78388337","21":"47632687","22":"223834163","23":"4355854","24":"15967622","25":"Billie Eilish","26":"bad guy","27":"2019-03-28","28":"Rock","29":"Universal Music","30":"TRUE","31":"good"},{"1":"DEUM71807062","2":"550208","3":"1419867299","4":"674","5":"35","6":"50.1","7":"40.5","8":"3.19","9":"0.00","10":"10.50","11":"44.6","12":"109.891","13":"3.036017","14":"96.28571","15":"not explicit","16":"9248","17":"90","18":"346557905","19":"1500000","20":"5581593","21":"29822533","22":"146074472","23":"593695","24":"894017","25":"Lewis Capaldi","26":"Someone You Loved","27":"2018-11-08","28":"Rock","29":"Universal Music","30":"TRUE","31":"excellent"},{"1":"USUM71911283","2":"4934","3":"1156206588","4":"604","5":"35","6":"75.9","7":"54.8","8":"2.90","9":"0.00","10":"8.28","11":"74.9","12":"116.967","13":"3.180000","14":"91.57143","15":"not explicit","16":"9109","17":"83","18":"1215405738","19":"5700000","20":"59448876","21":"42568761","22":"257192162","23":"5613129","24":"12124023","25":"Shawn Mendes feat. Camila Cabello","26":"Señorita","27":"2019-06-19","28":"Pop","29":"Universal Music","30":"TRUE","31":"excellent"},{"1":"USUG11800208","2":"74419","3":"1103693478","4":"1099","5":"35","6":"74.0","7":"61.3","8":"14.50","9":"0.37","10":"12.30","11":"47.3","12":"75.023","13":"2.776767","14":"157.28571","15":"not explicit","16":"9537","17":"86","18":"1028957267","19":"1700000","20":"18761684","21":"27692936","22":"59707763","23":"2547427","24":"2906121","25":"XXXTENTACION","26":"SAD!","27":"2018-03-02","28":"Pop","29":"Universal Music","30":"TRUE","31":"excellent"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><strong>Task 3</strong></p>
<ol style="list-style-type: decimal">
<li>Determine the most popular genres.</li>
</ol>
<ul>
<li>Group the data by genre and calculate the total number of streams within each genre.</li>
<li>Sort the result to show the most popular genre first.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Create a bar plot in which the heights of the bars correspond to the total number of streams within a genre (Bonus: order the bars by their height)</li>
</ol>
<p>The correct order of the <code>dplyr</code> functions would be as follows: you first group the observations by genre, then summarize the streams using <code>sum()</code>, and finally arrange the sums of streams. If you create an object, don’t forget to print it to show the result:</p>
<div class="sourceCode" id="cb773"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb773-1"><a href="r-markdown.html#cb773-1" aria-hidden="true" tabindex="-1"></a>genres_popularity <span class="ot">&lt;-</span> music_data <span class="sc">|&gt;</span></span>
<span id="cb773-2"><a href="r-markdown.html#cb773-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(genre) <span class="sc">|&gt;</span></span>
<span id="cb773-3"><a href="r-markdown.html#cb773-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">streams =</span> <span class="fu">sum</span>(streams)) <span class="sc">|&gt;</span></span>
<span id="cb773-4"><a href="r-markdown.html#cb773-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(streams))</span>
<span id="cb773-5"><a href="r-markdown.html#cb773-5" aria-hidden="true" tabindex="-1"></a>genres_popularity</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["genre"],"name":[1],"type":["fct"],"align":["left"]},{"label":["streams"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"Pop","2":"173713597202"},{"1":"HipHop/Rap","2":"143116357087"},{"1":"other","2":"65952433233"},{"1":"Electro/Dance","2":"33815774273"},{"1":"Rock","2":"29085255798"},{"1":"R&B","2":"28843269808"},{"1":"Country","2":"7575073860"},{"1":"Soundtrack","2":"4132622529"},{"1":"German Folk","2":"1521744994"},{"1":"Reggae","2":"775976707"},{"1":"Classics/Jazz","2":"58854804"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Ideally, you should provide some <strong>textual conclusion</strong>, e.g., “as can be seen, Pop is the most popular genre when the total number of streams is considered”.</p>
<p>To create a bar plot, you need the data frame with the sums of streams by labels. Then you should use <code>ggplot()</code> function as follows:</p>
<div class="sourceCode" id="cb774"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb774-1"><a href="r-markdown.html#cb774-1" aria-hidden="true" tabindex="-1"></a>genres_popularity <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(genres_popularity)</span>
<span id="cb774-2"><a href="r-markdown.html#cb774-2" aria-hidden="true" tabindex="-1"></a><span class="co"># head(genres_popularity)</span></span>
<span id="cb774-3"><a href="r-markdown.html#cb774-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb774-4"><a href="r-markdown.html#cb774-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(colorspace)</span>
<span id="cb774-5"><a href="r-markdown.html#cb774-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(genres_popularity, <span class="fu">aes</span>(<span class="at">x =</span> genre, <span class="at">y =</span> streams)) <span class="sc">+</span></span>
<span id="cb774-6"><a href="r-markdown.html#cb774-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> streams)) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Total streams&quot;</span>) <span class="sc">+</span></span>
<span id="cb774-7"><a href="r-markdown.html#cb774-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Genre&quot;</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">scale_fill_continuous_sequential</span>(<span class="at">palette =</span> <span class="st">&quot;Purple-Orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb774-8"><a href="r-markdown.html#cb774-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.6</span>),</span>
<span id="cb774-9"><a href="r-markdown.html#cb774-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-4"></span>
<img src="14-rmdIntro_files/figure-html/unnamed-chunk-4-1.png" alt="Total streams by genre" width="672" />
<p class="caption">
Figure 1.3: Total streams by genre
</p>
</div>
<p><strong>Bonus:</strong> if you want to reorder the bars to clearly show the most/least popular genres, use function <code>fct_reorder()</code> from the package <code>forcats</code> (part of <code>tidyverse</code>):</p>
<div class="sourceCode" id="cb775"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb775-1"><a href="r-markdown.html#cb775-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(genres_popularity, <span class="fu">aes</span>(<span class="at">x =</span> genre, <span class="at">y =</span> streams)) <span class="sc">+</span></span>
<span id="cb775-2"><a href="r-markdown.html#cb775-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(genre, streams), <span class="at">fill =</span> streams)) <span class="sc">+</span></span>
<span id="cb775-3"><a href="r-markdown.html#cb775-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Total streams&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Genre&quot;</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb775-4"><a href="r-markdown.html#cb775-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_continuous_sequential</span>(<span class="at">palette =</span> <span class="st">&quot;Purple-Orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb775-5"><a href="r-markdown.html#cb775-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.6</span>),</span>
<span id="cb775-6"><a href="r-markdown.html#cb775-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-5"></span>
<img src="14-rmdIntro_files/figure-html/unnamed-chunk-5-1.png" alt="Total streams by genre, ordered" width="672" />
<p class="caption">
Figure 1.4: Total streams by genre, ordered
</p>
</div>
<p><strong>Task 4</strong></p>
<ol style="list-style-type: decimal">
<li>Rank the music labels by their success (total number of streams of all their songs)</li>
<li>Show the total number of streams as well as the average and the median of all songs by label. (Bonus: Also add the artist and track names and the number of streams of each label’s top song to the result)</li>
</ol>
<p>Just like in the previous task, it would be enough to group the observations (in this case, by labels), get the sums of streams, and arrange them:</p>
<div class="sourceCode" id="cb776"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb776-1"><a href="r-markdown.html#cb776-1" aria-hidden="true" tabindex="-1"></a>music_data <span class="sc">|&gt;</span></span>
<span id="cb776-2"><a href="r-markdown.html#cb776-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(label) <span class="sc">|&gt;</span></span>
<span id="cb776-3"><a href="r-markdown.html#cb776-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">total_streams =</span> <span class="fu">sum</span>(streams)) <span class="sc">|&gt;</span></span>
<span id="cb776-4"><a href="r-markdown.html#cb776-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(total_streams))</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["label"],"name":[1],"type":["fct"],"align":["left"]},{"label":["total_streams"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"Universal Music","2":"197499391883"},{"1":"Sony Music","2":"108111852495"},{"1":"Independent","2":"94289773362"},{"1":"Warner Music","2":"88689942555"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Again, you need to report the result of sorting, e.g., Universal Music is the leader by number of streams of their songs.</p>
<p>To add more descriptive statistics (mean and median), you should also use <code>summarize()</code>:</p>
<div class="sourceCode" id="cb777"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb777-1"><a href="r-markdown.html#cb777-1" aria-hidden="true" tabindex="-1"></a>music_data <span class="sc">|&gt;</span></span>
<span id="cb777-2"><a href="r-markdown.html#cb777-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(label) <span class="sc">|&gt;</span></span>
<span id="cb777-3"><a href="r-markdown.html#cb777-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">total_streams =</span> <span class="fu">sum</span>(streams), <span class="at">avg_streams =</span> <span class="fu">mean</span>(streams),</span>
<span id="cb777-4"><a href="r-markdown.html#cb777-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">median_streams =</span> <span class="fu">median</span>(streams)) <span class="sc">|&gt;</span></span>
<span id="cb777-5"><a href="r-markdown.html#cb777-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(total_streams))</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["label"],"name":[1],"type":["fct"],"align":["left"]},{"label":["total_streams"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["avg_streams"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["median_streams"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"Universal Music","2":"197499391883","3":"9129964","4":"434943.0"},{"1":"Sony Music","2":"108111852495","3":"8725735","4":"355898.5"},{"1":"Independent","2":"94289773362","3":"4177659","4":"238884.0"},{"1":"Warner Music","2":"88689942555","3":"8691684","4":"347152.5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Here, you can compare labels by means: for example, it’s already clear that Independent label(s) have more songs than Warner Music, thus it has more total streams; however, Warner Music’s songs are more successful than Independent’s in average streams.</p>
<p><strong>Bonus:</strong> to add most popular artists’ names and their hit songs, create three more columns using <code>first()</code> function from <code>dplyr</code> (you need to use <code>dplyr::first()</code> because the <code>first()</code> function exists in some other R packages):</p>
<div class="sourceCode" id="cb778"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb778-1"><a href="r-markdown.html#cb778-1" aria-hidden="true" tabindex="-1"></a>music_data <span class="sc">|&gt;</span></span>
<span id="cb778-2"><a href="r-markdown.html#cb778-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(label) <span class="sc">|&gt;</span></span>
<span id="cb778-3"><a href="r-markdown.html#cb778-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">total_streams =</span> <span class="fu">sum</span>(streams), <span class="at">avg_streams =</span> <span class="fu">mean</span>(streams),</span>
<span id="cb778-4"><a href="r-markdown.html#cb778-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">median_streams =</span> <span class="fu">median</span>(streams), <span class="at">artist =</span> dplyr<span class="sc">::</span><span class="fu">first</span>(artistName,</span>
<span id="cb778-5"><a href="r-markdown.html#cb778-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">order_by =</span> <span class="fu">desc</span>(streams)), <span class="at">song =</span> dplyr<span class="sc">::</span><span class="fu">first</span>(trackName,</span>
<span id="cb778-6"><a href="r-markdown.html#cb778-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">order_by =</span> <span class="fu">desc</span>(streams)), <span class="at">song_streams =</span> dplyr<span class="sc">::</span><span class="fu">first</span>(streams,</span>
<span id="cb778-7"><a href="r-markdown.html#cb778-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">order_by =</span> <span class="fu">desc</span>(streams))) <span class="sc">|&gt;</span></span>
<span id="cb778-8"><a href="r-markdown.html#cb778-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(total_streams))</span></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["label"],"name":[1],"type":["fct"],"align":["left"]},{"label":["total_streams"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["avg_streams"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["median_streams"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["artist"],"name":[5],"type":["chr"],"align":["left"]},{"label":["song"],"name":[6],"type":["chr"],"align":["left"]},{"label":["song_streams"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"Universal Music","2":"197499391883","3":"9129964","4":"434943.0","5":"Billie Eilish","6":"bad guy","7":"1459149566"},{"1":"Sony Music","2":"108111852495","3":"8725735","4":"355898.5","5":"Travis Scott","6":"SICKO MODE","7":"1032407145"},{"1":"Independent","2":"94289773362","3":"4177659","4":"238884.0","5":"XXXTENTACION","6":"Jocelyn Flores","7":"936906948"},{"1":"Warner Music","2":"88689942555","3":"8691684","4":"347152.5","5":"Ed Sheeran","6":"Shape of You","7":"2165692479"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><strong>Task 5</strong></p>
<ol style="list-style-type: decimal">
<li>How do genres differ in terms of song features (audio features + song length + explicitness + song age)?</li>
</ol>
<ul>
<li>Select appropriate summary statistics for each of the variables and highlight the differences between genres using the summary statistics.</li>
<li>Create an appropriate plot showing the differences of “energy” across genres.</li>
</ul>
<p>All audio features, song length and song age are variables measured on a <strong>ratio scale</strong>, which means that we can evaluate their <strong>average values</strong>. We can use <code>describeBy()</code> function, which displays mean by default alongside with median and range values. Let’s have a look at some of the features:</p>
<div class="sourceCode" id="cb779"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb779-1"><a href="r-markdown.html#cb779-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb779-2"><a href="r-markdown.html#cb779-2" aria-hidden="true" tabindex="-1"></a><span class="fu">describeBy</span>(<span class="fu">select</span>(music_data, danceability, energy,</span>
<span id="cb779-3"><a href="r-markdown.html#cb779-3" aria-hidden="true" tabindex="-1"></a>    speechiness, song_length, song_age), music_data<span class="sc">$</span>genre)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: Classics/Jazz
##              vars  n   mean     sd median trimmed    mad   min     max   range
## danceability    1 80  46.00  18.34  46.60   46.05  20.39  7.33   83.70   76.37
## energy          2 80  30.85  19.51  28.10   29.00  18.46  0.26   85.00   84.74
## speechiness     3 80   6.11   6.55   3.92    4.53   1.15  2.46   46.70   44.24
## song_length     4 80   3.69   1.29   3.46    3.65   1.14  0.82    7.98    7.16
## song_age        5 80 819.66 780.21 590.93  689.94 572.28 17.29 4255.29 4238.00
##               skew kurtosis    se
## danceability -0.05    -0.74  2.05
## energy        0.72    -0.03  2.18
## speechiness   3.89    18.08  0.73
## song_length   0.45     0.53  0.14
## song_age      1.78     4.00 87.23
## ------------------------------------------------------------ 
## group: Country
##              vars   n   mean     sd median trimmed   mad   min     max   range
## danceability    1 504  59.67  11.98  59.70   59.64  9.49 19.20   92.20   73.00
## energy          2 504  69.71  18.71  75.00   71.50 17.12  4.84   97.70   92.86
## speechiness     3 504   5.16   4.10   3.78    4.28  1.30  2.48   35.10   32.62
## song_length     4 504   3.35   0.54   3.27    3.31  0.48  1.69    5.40    3.70
## song_age        5 504 244.21 437.55 109.29  133.08 99.33  2.29 2755.14 2752.86
##               skew kurtosis    se
## danceability -0.05     0.40  0.53
## energy       -0.85     0.16  0.83
## speechiness   3.97    20.41  0.18
## song_length   0.81     1.18  0.02
## song_age      3.51    12.80 19.49
## ------------------------------------------------------------ 
## group: Electro/Dance
##              vars    n   mean     sd median trimmed   mad   min     max   range
## danceability    1 2703  66.55  11.87  67.40   67.09 11.42 22.40   97.30   74.90
## energy          2 2703  74.51  13.99  76.20   75.58 13.49  2.62   99.90   97.28
## speechiness     3 2703   7.82   6.33   5.38    6.46  2.59  2.37   47.40   45.03
## song_length     4 2703   3.36   0.74   3.25    3.28  0.49  0.56    9.83    9.27
## song_age        5 2703 187.77 194.72 157.29  154.42 84.51  3.14 2285.57 2282.43
##               skew kurtosis   se
## danceability -0.45     0.22 0.23
## energy       -0.85     1.08 0.27
## speechiness   2.52     7.77 0.12
## song_length   2.59    13.64 0.01
## song_age      4.48    28.86 3.75
## ------------------------------------------------------------ 
## group: German Folk
##              vars   n   mean     sd median trimmed   mad   min     max   range
## danceability    1 539  63.03  15.36  65.20   63.81 15.57 20.60   96.40   75.80
## energy          2 539  61.73  22.56  66.60   63.03 25.06  5.48   99.90   94.42
## speechiness     3 539   9.80  10.20   4.91    7.57  2.67  2.45   49.90   47.45
## song_length     4 539   3.65   0.97   3.63    3.64  0.76  0.72    6.93    6.22
## song_age        5 539 436.39 552.94 212.29  301.88 70.53  3.29 2985.57 2982.29
##               skew kurtosis    se
## danceability -0.42    -0.40  0.66
## energy       -0.44    -0.85  0.97
## speechiness   1.77     2.18  0.44
## song_length  -0.06     1.23  0.04
## song_age      2.44     5.37 23.82
## ------------------------------------------------------------ 
## group: HipHop/Rap
##              vars     n   mean    sd median trimmed   mad  min     max   range
## danceability    1 21131  73.05 12.30  74.80   73.86 11.86 8.39   98.00   89.61
## energy          2 21131  65.10 13.28  65.70   65.41 13.49 0.54   99.00   98.46
## speechiness     3 21131  20.92 13.55  19.00   19.74 15.72 2.54   96.60   94.06
## song_length     4 21131   3.22  0.81   3.14    3.17  0.61 0.50   29.78   29.28
## song_age        5 21131 109.30 96.83  96.29  100.31 75.40 0.29 1837.57 1837.29
##               skew kurtosis   se
## danceability -0.63     0.16 0.08
## energy       -0.31     0.20 0.09
## speechiness   0.84     0.97 0.09
## song_length   5.28   125.03 0.01
## song_age      5.37    55.22 0.67
## ------------------------------------------------------------ 
## group: other
##              vars    n   mean     sd median trimmed    mad  min     max   range
## danceability    1 5228  64.53  15.39  67.00   65.81  14.53 7.83   96.70   88.87
## energy          2 5228  63.91  20.46  67.70   65.58  20.76 3.32   98.80   95.48
## speechiness     3 5228   9.30  10.38   5.58    7.12   3.39 2.36   95.50   93.14
## song_length     4 5228   3.43   0.96   3.35    3.38   0.72 0.53   22.17   21.64
## song_age        5 5228 395.45 651.78 142.43  230.38 130.68 0.43 4268.43 4268.00
##               skew kurtosis   se
## danceability -0.75     0.35 0.21
## energy       -0.65    -0.29 0.28
## speechiness   4.09    24.16 0.14
## song_length   3.47    50.56 0.01
## song_age      2.80     8.07 9.01
## ------------------------------------------------------------ 
## group: Pop
##              vars     n   mean     sd median trimmed   mad  min     max   range
## danceability    1 30069  63.74  14.46  65.10   64.39 14.53 0.00   98.30   98.30
## energy          2 30069  62.91  18.62  65.00   63.97 19.13 0.00  100.00  100.00
## speechiness     3 30069   9.85  10.20   5.37    7.58  3.28 0.00   95.60   95.60
## song_length     4 30069   3.52   0.84   3.43    3.47  0.65 0.02   29.35   29.34
## song_age        5 30069 238.36 374.54 143.29  150.48 99.12 0.29 6325.00 6324.71
##               skew kurtosis   se
## danceability -0.42    -0.09 0.08
## energy       -0.49    -0.22 0.11
## speechiness   2.36     7.21 0.06
## song_length   3.02    52.35 0.00
## song_age      4.28    25.68 2.16
## ------------------------------------------------------------ 
## group: R&amp;B
##              vars    n   mean     sd median trimmed   mad  min     max   range
## danceability    1 1881  67.97  13.43  70.10   69.07 12.60 8.66   97.00   88.34
## energy          2 1881  61.25  15.80  62.30   61.92 15.86 2.46   96.10   93.64
## speechiness     3 1881  12.34  10.10   8.38   10.59  6.33 2.29   85.60   83.31
## song_length     4 1881   3.46   0.72   3.43    3.43  0.63 0.89    8.53    7.64
## song_age        5 1881 229.74 460.38 109.71  118.87 82.39 2.29 3277.00 3274.71
##               skew kurtosis    se
## danceability -0.77     0.42  0.31
## energy       -0.42     0.01  0.36
## speechiness   1.69     3.64  0.23
## song_length   0.85     3.31  0.02
## song_age      4.43    20.72 10.62
## ------------------------------------------------------------ 
## group: Reggae
##              vars   n   mean     sd median trimmed    mad   min     max   range
## danceability    1 121  75.06   9.33  76.70   75.55   7.71 40.40   94.40   54.00
## energy          2 121  67.61  14.91  69.60   68.47  14.83 14.50   91.10   76.60
## speechiness     3 121  11.96   8.69   7.85   10.58   5.49  2.62   36.30   33.68
## song_length     4 121   3.50   0.57   3.44    3.43   0.52  2.48    5.37    2.89
## song_age        5 121 343.68 530.67 152.29  219.77 126.02 13.29 2307.14 2293.86
##               skew kurtosis    se
## danceability -0.66     0.89  0.85
## energy       -0.66     0.52  1.36
## speechiness   1.16     0.44  0.79
## song_length   1.00     0.98  0.05
## song_age      2.67     6.75 48.24
## ------------------------------------------------------------ 
## group: Rock
##              vars    n   mean     sd median trimmed    mad  min     max   range
## danceability    1 4214  54.75  13.98  55.00   55.05  13.79 6.28   98.00   91.72
## energy          2 4214  67.77  21.37  70.85   69.41  23.35 1.37   99.80   98.43
## speechiness     3 4214   6.19   5.22   4.32    5.03   1.82 2.22   54.60   52.38
## song_length     4 4214   3.85   0.99   3.72    3.78   0.73 0.66   15.73   15.06
## song_age        5 4214 356.17 531.81 160.29  223.63 112.68 1.29 3309.71 3308.43
##               skew kurtosis   se
## danceability -0.21     0.02 0.22
## energy       -0.58    -0.44 0.33
## speechiness   3.34    14.68 0.08
## song_length   2.11    15.15 0.02
## song_age      2.52     6.17 8.19
## ------------------------------------------------------------ 
## group: Soundtrack
##              vars   n   mean     sd median trimmed   mad   min     max   range
## danceability    1 326  52.82  16.25  54.10   52.84 17.79 15.00   91.50   76.50
## energy          2 326  52.05  21.96  50.20   52.24 22.98  1.26   97.90   96.64
## speechiness     3 326   6.82   7.51   3.99    5.17  1.46  2.42   81.80   79.38
## song_length     4 326   3.55   0.99   3.50    3.54  0.80  0.77    8.84    8.07
## song_age        5 326 230.16 318.20 147.29  162.42 81.54  3.43 3068.29 3064.86
##               skew kurtosis    se
## danceability -0.03    -0.70  0.90
## energy       -0.05    -0.58  1.22
## speechiness   4.59    33.21  0.42
## song_length   0.50     3.06  0.05
## song_age      4.73    28.67 17.62</code></pre>
<p><strong>Please note that it is not enough to simply print the means.</strong> You should always explain (a.k.a. “highlight”) the differences between genres in terms of song features:</p>
<ul>
<li>on average, Reggae and HipHop are the most danceable genres (their mean danceabilities are 75.06 and 73.05, respectively);</li>
<li>Rock songs have the longest average song duration across all genres (3.85 min);</li>
<li>Classic and Jazz songs are the oldest (average song age is 819.66 weeks);</li>
<li>etc.</li>
</ul>
<p>However, explicitness is a <strong>categorical (nominal) variable</strong>, i.e., <strong>we cannot use mean or median</strong> to describe genres by explicitness. To describe genres by it, we should get and examine the frequencies of explicit and not explicit songs:</p>
<div class="sourceCode" id="cb781"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb781-1"><a href="r-markdown.html#cb781-1" aria-hidden="true" tabindex="-1"></a><span class="co"># table(select(music_data, genre, explicit))</span></span>
<span id="cb781-2"><a href="r-markdown.html#cb781-2" aria-hidden="true" tabindex="-1"></a><span class="co"># #absolute frequencies</span></span>
<span id="cb781-3"><a href="r-markdown.html#cb781-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(<span class="fu">select</span>(music_data, genre, explicit)),</span>
<span id="cb781-4"><a href="r-markdown.html#cb781-4" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb781-5"><a href="r-markdown.html#cb781-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">round</span>(<span class="dv">3</span>)  <span class="co">#relative frequencies</span></span></code></pre></div>
<pre><code>##                explicit
## genre           not explicit explicit
##   Classics/Jazz        0.825    0.175
##   Country              0.980    0.020
##   Electro/Dance        0.660    0.340
##   German Folk          0.701    0.299
##   HipHop/Rap           0.948    0.052
##   other                0.922    0.078
##   Pop                  0.845    0.155
##   R&amp;B                  0.922    0.078
##   Reggae               0.909    0.091
##   Rock                 0.828    0.172
##   Soundtrack           0.868    0.132</code></pre>
<p>This can also be visualized with a grouped bar chart:</p>
<div class="sourceCode" id="cb783"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb783-1"><a href="r-markdown.html#cb783-1" aria-hidden="true" tabindex="-1"></a><span class="co">#genres_explicit &lt;- as.data.frame(table(select(music_data, genre, explicit)))  #absolute frequencies</span></span>
<span id="cb783-2"><a href="r-markdown.html#cb783-2" aria-hidden="true" tabindex="-1"></a>genres_explicit_rel <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(<span class="fu">select</span>(music_data, genre, explicit)), <span class="dv">1</span>))  <span class="co">#relative frequencies</span></span>
<span id="cb783-3"><a href="r-markdown.html#cb783-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb783-4"><a href="r-markdown.html#cb783-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(colorspace)</span>
<span id="cb783-5"><a href="r-markdown.html#cb783-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(genres_explicit_rel, </span>
<span id="cb783-6"><a href="r-markdown.html#cb783-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> genre, <span class="at">y =</span> Freq, <span class="at">fill =</span> explicit)) <span class="sc">+</span> <span class="co">#use &quot;fill&quot; argument for different colors</span></span>
<span id="cb783-7"><a href="r-markdown.html#cb783-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="sc">+</span> <span class="co">#use &quot;dodge&quot; to display bars next to each other (instead of stacked on top)</span></span>
<span id="cb783-8"><a href="r-markdown.html#cb783-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.0f%%&quot;</span>, Freq <span class="sc">*</span> <span class="dv">100</span>)), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.25</span>) <span class="sc">+</span> <span class="co">#labels in %</span></span>
<span id="cb783-9"><a href="r-markdown.html#cb783-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete_qualitative</span>(<span class="at">palette =</span> <span class="st">&quot;Dynamic&quot;</span>) <span class="sc">+</span></span>
<span id="cb783-10"><a href="r-markdown.html#cb783-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Genre&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Relative frequency&quot;</span>) <span class="sc">+</span> </span>
<span id="cb783-11"><a href="r-markdown.html#cb783-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb783-12"><a href="r-markdown.html#cb783-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete_sequential</span>(<span class="at">palette =</span> <span class="st">&quot;PurpOr&quot;</span>) <span class="sc">+</span></span>
<span id="cb783-13"><a href="r-markdown.html#cb783-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">1.1</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-6"></span>
<img src="14-rmdIntro_files/figure-html/unnamed-chunk-6-1.png" alt="Explicit lyrics share by genre" width="672" />
<p class="caption">
Figure 5.1: Explicit lyrics share by genre
</p>
</div>
<p>From the plot above it can be concluded, that Electro/Dance has the greatest share of explicit songs across all genres (34%); Country, in contrast, has the least share of explicit songs (only 2%).</p>
<p>For showing the differences in energy in songs across genres, it would make sense to plot the means of all genres’ songs’ energy using boxplot:</p>
<div class="sourceCode" id="cb784"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb784-1"><a href="r-markdown.html#cb784-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(music_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(genre, energy),</span>
<span id="cb784-2"><a href="r-markdown.html#cb784-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> energy)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">coef =</span> <span class="dv">3</span>, <span class="at">fill =</span> <span class="st">&quot;lavenderblush3&quot;</span>,</span>
<span id="cb784-3"><a href="r-markdown.html#cb784-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;thistle4&quot;</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Genre&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Energy&quot;</span>) <span class="sc">+</span></span>
<span id="cb784-4"><a href="r-markdown.html#cb784-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>,</span>
<span id="cb784-5"><a href="r-markdown.html#cb784-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="fl">1.1</span>, <span class="at">hjust =</span> <span class="dv">1</span>), <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-7"></span>
<img src="14-rmdIntro_files/figure-html/unnamed-chunk-7-1.png" alt="Boxplot of energy by genre" width="672" />
<p class="caption">
Figure 1.5: Boxplot of energy by genre
</p>
</div>
<p>Also, you could have a look at the plot of means:</p>
<div class="sourceCode" id="cb785"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb785-1"><a href="r-markdown.html#cb785-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Rmisc)</span>
<span id="cb785-2"><a href="r-markdown.html#cb785-2" aria-hidden="true" tabindex="-1"></a>mean_data <span class="ot">&lt;-</span> <span class="fu">summarySE</span>(music_data, <span class="at">measurevar =</span> <span class="st">&quot;energy&quot;</span>,</span>
<span id="cb785-3"><a href="r-markdown.html#cb785-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">groupvars =</span> <span class="st">&quot;genre&quot;</span>)</span>
<span id="cb785-4"><a href="r-markdown.html#cb785-4" aria-hidden="true" tabindex="-1"></a><span class="co"># mean_data</span></span>
<span id="cb785-5"><a href="r-markdown.html#cb785-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb785-6"><a href="r-markdown.html#cb785-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mean_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(genre, energy),</span>
<span id="cb785-7"><a href="r-markdown.html#cb785-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> energy)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.9</span>),</span>
<span id="cb785-8"><a href="r-markdown.html#cb785-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;lavenderblush3&quot;</span>, <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">width =</span> <span class="fl">0.55</span>) <span class="sc">+</span></span>
<span id="cb785-9"><a href="r-markdown.html#cb785-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_errorbar</span>(<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.9</span>), <span class="at">width =</span> <span class="fl">0.15</span>,</span>
<span id="cb785-10"><a href="r-markdown.html#cb785-10" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>(<span class="at">ymin =</span> energy <span class="sc">-</span> ci, <span class="at">ymax =</span> energy <span class="sc">+</span> ci)) <span class="sc">+</span></span>
<span id="cb785-11"><a href="r-markdown.html#cb785-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Genre&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average energy of songs&quot;</span>) <span class="sc">+</span></span>
<span id="cb785-12"><a href="r-markdown.html#cb785-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.8</span>,</span>
<span id="cb785-13"><a href="r-markdown.html#cb785-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-8"></span>
<img src="14-rmdIntro_files/figure-html/unnamed-chunk-8-1.png" alt="Average energy of songs by genre" width="672" />
<p class="caption">
Figure 1.6: Average energy of songs by genre
</p>
</div>
<p><strong>Task 6</strong></p>
<p>Visualize the number of songs by label.</p>
<p>“Visualize” means “create a plot”. Thus, you should create a bar plot (to show differences in sum of streams by labels, where labels are categorical variables).
It is enough to visualize count of all observations by labels, i.e., it was not necessary to drop duplicates or repeated ISRCs. However, both solutions are correct.</p>
<div class="sourceCode" id="cb786"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb786-1"><a href="r-markdown.html#cb786-1" aria-hidden="true" tabindex="-1"></a>labels_songs <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">table</span>(music_data<span class="sc">$</span>label))  <span class="co"># frequencies</span></span>
<span id="cb786-2"><a href="r-markdown.html#cb786-2" aria-hidden="true" tabindex="-1"></a>labels_songs <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">rename</span>(labels_songs, <span class="at">label =</span> Var1,</span>
<span id="cb786-3"><a href="r-markdown.html#cb786-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">number_of_songs =</span> Freq)</span>
<span id="cb786-4"><a href="r-markdown.html#cb786-4" aria-hidden="true" tabindex="-1"></a><span class="co"># labels_songs</span></span></code></pre></div>
<div class="sourceCode" id="cb787"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb787-1"><a href="r-markdown.html#cb787-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(labels_songs, <span class="fu">aes</span>(<span class="at">x =</span> label, <span class="at">y =</span> number_of_songs)) <span class="sc">+</span></span>
<span id="cb787-2"><a href="r-markdown.html#cb787-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.55</span>, <span class="at">fill =</span> <span class="st">&quot;lavenderblush3&quot;</span>) <span class="sc">+</span></span>
<span id="cb787-3"><a href="r-markdown.html#cb787-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">&quot;Number of songs&quot;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Label&quot;</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-9"></span>
<img src="14-rmdIntro_files/figure-html/unnamed-chunk-9-1.png" alt="Count of songs by label" width="672" />
<p class="caption">
Figure 1.7: Count of songs by label
</p>
</div>
<p>Here we can see a confirmation of one of our previous conclusions about the difference in songs count between Warner Music and Independent labels, which resulted in the lower average streams of the latter.</p>
<p><strong>Task 7</strong></p>
<p>Visualize the share/relative frequency of songs by genre.</p>
<p>Again, you need to build an appropriate plot. It is a bar plot again, but it illustrates the relative frequencies between number of songs by genres. First, create a data frame with relative frequencies:</p>
<div class="sourceCode" id="cb788"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb788-1"><a href="r-markdown.html#cb788-1" aria-hidden="true" tabindex="-1"></a>genres_songs_rel <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(music_data<span class="sc">$</span>genre)))  <span class="co">#relative frequencies</span></span>
<span id="cb788-2"><a href="r-markdown.html#cb788-2" aria-hidden="true" tabindex="-1"></a>genres_songs_rel <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">rename</span>(genres_songs_rel,</span>
<span id="cb788-3"><a href="r-markdown.html#cb788-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">genre =</span> Var1, <span class="at">share =</span> Freq)</span>
<span id="cb788-4"><a href="r-markdown.html#cb788-4" aria-hidden="true" tabindex="-1"></a><span class="co"># head(genres_songs_rel)</span></span></code></pre></div>
<p>Then create the bar plot as usual:</p>
<div class="sourceCode" id="cb789"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb789-1"><a href="r-markdown.html#cb789-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(genres_songs_rel, <span class="fu">aes</span>(<span class="at">x =</span> genre, <span class="at">y =</span> share)) <span class="sc">+</span></span>
<span id="cb789-2"><a href="r-markdown.html#cb789-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> share)) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Share of songs&quot;</span>) <span class="sc">+</span></span>
<span id="cb789-3"><a href="r-markdown.html#cb789-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Label&quot;</span>) <span class="sc">+</span> <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">&quot;%.0f%%&quot;</span>,</span>
<span id="cb789-4"><a href="r-markdown.html#cb789-4" aria-hidden="true" tabindex="-1"></a>    share <span class="sc">*</span> <span class="dv">100</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.2</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb789-5"><a href="r-markdown.html#cb789-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_continuous_sequential</span>(<span class="at">palette =</span> <span class="st">&quot;Purple-Orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb789-6"><a href="r-markdown.html#cb789-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.75</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-10"></span>
<img src="14-rmdIntro_files/figure-html/unnamed-chunk-10-1.png" alt="Share of songs by genre" width="672" />
<p class="caption">
Figure 1.8: Share of songs by genre
</p>
</div>
<p><strong>Task 8</strong></p>
<p>Create a histogram of the variable “valence”.</p>
<p>This is a simple plot of valence distribution across all songs in your data (we can see that it follows normal distribution):</p>
<div class="sourceCode" id="cb790"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb790-1"><a href="r-markdown.html#cb790-1" aria-hidden="true" tabindex="-1"></a>music_data <span class="sc">|&gt;</span></span>
<span id="cb790-2"><a href="r-markdown.html#cb790-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(valence)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">4</span>,</span>
<span id="cb790-3"><a href="r-markdown.html#cb790-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;lavenderblush3&quot;</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Valence&quot;</span>,</span>
<span id="cb790-4"><a href="r-markdown.html#cb790-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-11"></span>
<img src="14-rmdIntro_files/figure-html/unnamed-chunk-11-1.png" alt="Distribution of valence" width="672" />
<p class="caption">
Figure 1.9: Distribution of valence
</p>
</div>
<p><strong>Task 9</strong></p>
<p>Create a scatter plot showing “valence” and “speechiness” (Bonus: add a regression line).</p>
<p>Finally, we can visualize the relationship between valence and speechiness of songs in our data:</p>
<div class="sourceCode" id="cb791"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb791-1"><a href="r-markdown.html#cb791-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(music_data, <span class="fu">aes</span>(speechiness, valence)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb791-2"><a href="r-markdown.html#cb791-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Speechiness&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Valence&quot;</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Speechiness&quot;</span>,</span>
<span id="cb791-3"><a href="r-markdown.html#cb791-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Valence&quot;</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-12"></span>
<img src="14-rmdIntro_files/figure-html/unnamed-chunk-12-1.png" alt="Scatterplot of speechiness and valence" width="672" />
<p class="caption">
Figure 1.10: Scatterplot of speechiness and valence
</p>
</div>
<p><strong>Bonus:</strong> to add regression line, use <code>geom_smooth()</code> function:</p>
<div class="sourceCode" id="cb792"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb792-1"><a href="r-markdown.html#cb792-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(music_data, </span>
<span id="cb792-2"><a href="r-markdown.html#cb792-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(speechiness, valence)) <span class="sc">+</span></span>
<span id="cb792-3"><a href="r-markdown.html#cb792-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Speechiness&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Valence&quot;</span>) <span class="sc">+</span></span>
<span id="cb792-4"><a href="r-markdown.html#cb792-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;lavenderblush4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span> <span class="co">#add regression line</span></span>
<span id="cb792-5"><a href="r-markdown.html#cb792-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Speechiness&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Valence&quot;</span>) <span class="sc">+</span></span>
<span id="cb792-6"><a href="r-markdown.html#cb792-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-13"></span>
<img src="14-rmdIntro_files/figure-html/unnamed-chunk-13-1.png" alt="Scatterplot of speechiness and valence" width="672" />
<p class="caption">
Figure 1.11: Scatterplot of speechiness and valence
</p>
</div>
<p>The slope of the regression line suggests that there is positive relationship between valence and speechiness.</p>

<p><link rel="stylesheet" type="text/css" media="all" href="style.css" /></p>
</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="cluster-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="survey-design-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
